// SPDX-License-Identifier: MIT
// Stub SDK header for M_ActuationCtrl.
#pragma once
#include "M_ActuationCtrl_stub.hpp"   // generated by pipegen (struct types + IClient/IService shells)
#include <memory>
#include <string>

namespace M_ActuationCtrl {

class Client {
public:
    static std::unique_ptr<Client> create(int domainId, std::string serviceName, IClient& cb);
    ~Client();
    // Inline no-op IService command forwarders (stub).
    void CmdIsActuationAlive() {}
    void ConfigActuationComponentReference(::std::string const& /*unused*/, ActuationCommandType const& /*unused*/, bool const& /*unused*/, bool const& /*unused*/) {}
    void NotifyActuationComponentCommand(::std::string const& /*unused*/, ActuationCommandType const& /*unused*/) {}
    // Inline no-op IClient report forwarders (stub).
    void ReportActuationCtrlSettings(ActuationCtrlSettingsType const& /*unused*/) {}
    void ReportActuationComponentStatus(::std::string const& /*unused*/, ActuationStatusType const& /*unused*/, bool const& /*unused*/) {}



private:
    Client(int domain, std::string svc, IClient& cb);
    int sub_id_ = -1;
};

class Service {
public:
    static std::unique_ptr<Service> create(int domainId, std::string serviceName, IService& cb);
    ~Service();
    // Inline no-op IClient report forwarders (stub).
    void ReportActuationCtrlSettings(ActuationCtrlSettingsType const& /*unused*/) {}
    void ReportActuationComponentStatus(::std::string const& /*unused*/, ActuationStatusType const& /*unused*/, bool const& /*unused*/) {}
    // Inline no-op IService command forwarders (stub).
    void CmdIsActuationAlive() {}
    void ConfigActuationComponentReference(::std::string const& /*unused*/, ActuationCommandType const& /*unused*/, bool const& /*unused*/, bool const& /*unused*/) {}
    void NotifyActuationComponentCommand(::std::string const& /*unused*/, ActuationCommandType const& /*unused*/) {}



private:
    Service(int domain, std::string svc, IService& cb);
    int sub_id_ = -1;
};

}  // namespace M_ActuationCtrl
