// SPDX-License-Identifier: MIT
#pragma once
#include "M_Alert_stub.hpp"   // generated by pipegen (struct types + IClient/IService shells)
#include <memory>
#include <string>

namespace M_Alert {

class Service {
public:
    static std::unique_ptr<Service> create(int domainId, std::string serviceName, IService&);
    ~Service();
    // Inline no-op IClient report forwarders (stub).
    void ReportAlertSettings(AlertSettingsType const& /*unused*/) {}
    void ReportAlertStatus(AlertStatusType const& /*unused*/, bool const& /*unused*/) {}
    void ReportAlarmLog(AlertIdType const& /*unused*/, AlarmLogType const& /*unused*/, bool const& /*unused*/) {}
    void ReportAlarmAnnunciation(::std::string const& /*unused*/, AlarmAnnunciationType const& /*unused*/, bool const& /*unused*/) {}
    void ReportThreatLog(AlertIdType const& /*unused*/, ThreatLogType const& /*unused*/, bool const& /*unused*/) {}
    void ReportThreatAnnunciation(ThreatAnnunciationType const& /*unused*/, bool const& /*unused*/) {}
    // Inline no-op IService command forwarders (stub).
    void CmdRaiseAlarm(AlarmConditionInfoType const& /*unused*/) {}
    void CmdResolveAlarm(AlarmConditionInfoType const& /*unused*/) {}
    void CmdAcknowledgeAlarm(AlertIdListType const& /*unused*/) {}
    void CmdOverrideAlarmCondition(AlarmConditionInfoType const& /*unused*/) {}
    void CmdUnoverrideAlarmCondition(AlarmConditionInfoType const& /*unused*/) {}
    void CmdClearAlarm(AlertIdListType const& /*unused*/) {}
    void CmdRaiseThreatAlert(AlertIdType const& /*unused*/, ThreatLogType const& /*unused*/) {}
    void CmdCancelThreatAlert(AlertIdListType const& /*unused*/) {}



private:
    Service(int domain, std::string svc, IService& cb);
    int sub_id_;
};

// Alert.Client — both receives callbacks (IClient) and can publish commands.
class Client {
public:
    static std::unique_ptr<Client> create(int domainId, std::string serviceName, IClient& cb);
    ~Client();

    void CmdRaiseAlarm(AlarmConditionInfoType const& c);
    void CmdResolveAlarm(AlarmConditionInfoType const& c);
    void CmdOverrideAlarmCondition(AlarmConditionInfoType const& c);
    void CmdUnoverrideAlarmCondition(AlarmConditionInfoType const& c);
    // Inline no-op IService command forwarders (stub).
    void CmdAcknowledgeAlarm(AlertIdListType const& /*unused*/) {}
    void CmdClearAlarm(AlertIdListType const& /*unused*/) {}
    void CmdRaiseThreatAlert(AlertIdType const& /*unused*/, ThreatLogType const& /*unused*/) {}
    void CmdCancelThreatAlert(AlertIdListType const& /*unused*/) {}
    // Inline no-op IClient report forwarders (stub).
    void ReportAlertSettings(AlertSettingsType const& /*unused*/) {}
    void ReportAlertStatus(AlertStatusType const& /*unused*/, bool const& /*unused*/) {}
    void ReportAlarmLog(AlertIdType const& /*unused*/, AlarmLogType const& /*unused*/, bool const& /*unused*/) {}
    void ReportAlarmAnnunciation(::std::string const& /*unused*/, AlarmAnnunciationType const& /*unused*/, bool const& /*unused*/) {}
    void ReportThreatLog(AlertIdType const& /*unused*/, ThreatLogType const& /*unused*/, bool const& /*unused*/) {}
    void ReportThreatAnnunciation(ThreatAnnunciationType const& /*unused*/, bool const& /*unused*/) {}



private:
    Client(int domain, std::string svc, IClient& cb);
    int         domain_;
    std::string svc_;
    int         sub_id_ = -1;
};

}  // namespace M_Alert
