// SPDX-License-Identifier: MIT
// Stub SDK header for M_Alignment.
#pragma once
#include "M_Alignment_stub.hpp"   // generated by pipegen (struct types + IClient/IService shells)
#include <memory>
#include <string>

namespace M_Alignment {

class Client {
public:
    static std::unique_ptr<Client> create(int domainId, std::string serviceName, IClient& cb);
    ~Client();

    // No-op IService command forwarders (stub implementation).
    void CmdSaveAlignment(::std::string const& /*unused*/) {}
    void CmdClearAlignment(::std::string const& /*unused*/) {}
    // Inline no-op IService command forwarders (stub).
    void CmdAlignmentState(::std::string const& /*unused*/, bool const& /*unused*/, ::M_Common::BooleanOptionalType const& /*unused*/) {}
    void CmdLateralAlignment(::std::string const& /*unused*/, ::M_Common::SphericalPositionType const& /*unused*/) {}
    void CmdLongitudinalAlignment(::std::string const& /*unused*/, ::M_Common::AngleDegreesType const& /*unused*/) {}
    void CmdAllowExternalAlignment(::std::string const& /*unused*/, bool const& /*unused*/) {}
    // Inline no-op IClient report forwarders (stub).
    void ReportAlignmentSettings(AlignmentSettingsType const& /*unused*/) {}
    void ReportAlignmentStatus(::std::string const& /*unused*/, AlignmentStatusType const& /*unused*/, bool const& /*unused*/) {}



private:
    Client(int domain, std::string svc, IClient& cb);
    int sub_id_ = -1;
};

class Service {
public:
    static std::unique_ptr<Service> create(int domainId, std::string serviceName, IService& cb);
    ~Service();
    // Inline no-op IClient report forwarders (stub).
    void ReportAlignmentSettings(AlignmentSettingsType const& /*unused*/) {}
    void ReportAlignmentStatus(::std::string const& /*unused*/, AlignmentStatusType const& /*unused*/, bool const& /*unused*/) {}
    // Inline no-op IService command forwarders (stub).
    void CmdAlignmentState(::std::string const& /*unused*/, bool const& /*unused*/, ::M_Common::BooleanOptionalType const& /*unused*/) {}
    void CmdLateralAlignment(::std::string const& /*unused*/, ::M_Common::SphericalPositionType const& /*unused*/) {}
    void CmdLongitudinalAlignment(::std::string const& /*unused*/, ::M_Common::AngleDegreesType const& /*unused*/) {}
    void CmdSaveAlignment(::std::string const& /*unused*/) {}
    void CmdClearAlignment(::std::string const& /*unused*/) {}
    void CmdAllowExternalAlignment(::std::string const& /*unused*/, bool const& /*unused*/) {}



private:
    Service(int domain, std::string svc, IService& cb);
    int sub_id_ = -1;
};

}  // namespace M_Alignment
