// SPDX-License-Identifier: MIT
// Stub SDK header for M_AnalogueIo.
#pragma once
#include "M_AnalogueIo_stub.hpp"   // generated by pipegen (struct types + IClient/IService shells)
#include <memory>
#include <string>

namespace M_AnalogueIo {

class Client {
public:
    static std::unique_ptr<Client> create(int domainId, std::string serviceName, IClient& cb);
    ~Client();
    // Inline no-op IService command forwarders (stub).
    void ConfigSignalCorridor(::std::string const& /*unused*/, SignalCorridorType const& /*unused*/, bool const& /*unused*/) {}
    void NotifySignal(::std::string const& /*unused*/, SignalType const& /*unused*/) {}
    // Inline no-op IClient report forwarders (stub).
    void ReportSignal(::std::string const& /*unused*/, SignalCorridorOptionalType const& /*unused*/, SignalOptionalType const& /*unused*/, bool const& /*unused*/) {}



private:
    Client(int domain, std::string svc, IClient& cb);
    int sub_id_ = -1;
};

class Service {
public:
    static std::unique_ptr<Service> create(int domainId, std::string serviceName, IService& cb);
    ~Service();
    // Inline no-op IClient report forwarders (stub).
    void ReportSignal(::std::string const& /*unused*/, SignalCorridorOptionalType const& /*unused*/, SignalOptionalType const& /*unused*/, bool const& /*unused*/) {}
    // Inline no-op IService command forwarders (stub).
    void ConfigSignalCorridor(::std::string const& /*unused*/, SignalCorridorType const& /*unused*/, bool const& /*unused*/) {}
    void NotifySignal(::std::string const& /*unused*/, SignalType const& /*unused*/) {}



private:
    Service(int domain, std::string svc, IService& cb);
    int sub_id_ = -1;
};

}  // namespace M_AnalogueIo
