// SPDX-License-Identifier: MIT
// Stub SDK header for M_Auth.
#pragma once
#include "M_Auth_stub.hpp"   // generated by pipegen (struct types + IClient/IService shells)
#include <memory>
#include <string>

namespace M_Auth {

class Client {
public:
    static std::unique_ptr<Client> create(int domainId, std::string serviceName, IClient& cb);
    ~Client();

    // No-op IService command forwarders (stub implementation).
    void CmdLogoutUser(::std::string const& /*unused*/) {}
    // Inline no-op IClient report forwarders (stub).
    void EventLogin(::std::string const& /*unused*/, LoginEventType const& /*unused*/) {}
    void ReportAuthStatus(::std::string const& /*unused*/, AuthStatusType const& /*unused*/, bool const& /*unused*/) {}


private:
    Client(int domain, std::string svc, IClient& cb);
    int sub_id_ = -1;
};

class Service {
public:
    static std::unique_ptr<Service> create(int domainId, std::string serviceName, IService& cb);
    ~Service();
    // Inline no-op IClient report forwarders (stub).
    void EventLogin(::std::string const& /*unused*/, LoginEventType const& /*unused*/) {}
    void ReportAuthStatus(::std::string const& /*unused*/, AuthStatusType const& /*unused*/, bool const& /*unused*/) {}
    // Inline no-op IService command forwarders (stub).
    void CmdLogoutUser(::std::string const& /*unused*/) {}



private:
    Service(int domain, std::string svc, IService& cb);
    int sub_id_ = -1;
};

}  // namespace M_Auth
