// SPDX-License-Identifier: MIT
// Stub SDK header for M_BuiltInTest.
#pragma once
#include "M_BuiltInTest_stub.hpp"   // generated by pipegen (struct types + IClient/IService shells)
#include <memory>
#include <string>

namespace M_BuiltInTest {

class Client {
public:
    static std::unique_ptr<Client> create(int domainId, std::string serviceName, IClient& cb);
    ~Client();

    // No-op IService command forwarders (stub implementation).
    void CmdStartIBitRoutine(::std::string const& /*unused*/) {}
    void CmdCancelIBitRoutine(::std::string const& /*unused*/) {}
    // Inline no-op IClient report forwarders (stub).
    void ReportBitSettings(BitSettingsType const& /*unused*/) {}
    void ReportIBitRoutineStatus(::std::string const& /*unused*/, IBitRoutineState::Type const& /*unused*/, bool const& /*unused*/) {}
    void ReportIBitStatus(::std::string const& /*unused*/, BitStatusType const& /*unused*/, bool const& /*unused*/) {}
    void ReportPBitStatus(::std::string const& /*unused*/, BitStatusType const& /*unused*/, bool const& /*unused*/) {}
    void ReportCBitStatus(::std::string const& /*unused*/, BitStatusType const& /*unused*/, bool const& /*unused*/) {}


private:
    Client(int domain, std::string svc, IClient& cb);
    int sub_id_ = -1;
};

class Service {
public:
    static std::unique_ptr<Service> create(int domainId, std::string serviceName, IService& cb);
    ~Service();
    // Inline no-op IClient report forwarders (stub).
    void ReportBitSettings(BitSettingsType const& /*unused*/) {}
    void ReportIBitRoutineStatus(::std::string const& /*unused*/, IBitRoutineState::Type const& /*unused*/, bool const& /*unused*/) {}
    void ReportIBitStatus(::std::string const& /*unused*/, BitStatusType const& /*unused*/, bool const& /*unused*/) {}
    void ReportPBitStatus(::std::string const& /*unused*/, BitStatusType const& /*unused*/, bool const& /*unused*/) {}
    void ReportCBitStatus(::std::string const& /*unused*/, BitStatusType const& /*unused*/, bool const& /*unused*/) {}
    // Inline no-op IService command forwarders (stub).
    void CmdStartIBitRoutine(::std::string const& /*unused*/) {}
    void CmdCancelIBitRoutine(::std::string const& /*unused*/) {}



private:
    Service(int domain, std::string svc, IService& cb);
    int sub_id_ = -1;
};

}  // namespace M_BuiltInTest
