// SPDX-License-Identifier: MIT
// Stub SDK header for M_BuiltInTestCtrl.
#pragma once
#include "M_BuiltInTestCtrl_stub.hpp"   // generated by pipegen (struct types + IClient/IService shells)
#include <memory>
#include <string>

namespace M_BuiltInTestCtrl {

class Client {
public:
    static std::unique_ptr<Client> create(int domainId, std::string serviceName, IClient& cb);
    ~Client();

    // No-op IService command forwarders (stub implementation).
    void ConfigAllowTest(bool const& /*unused*/) {}
    void CmdStartTest(::std::string const& /*unused*/) {}
    // Inline no-op IService command forwarders (stub).
    void CmdCancelTest() {}
    void RequestHistoricalRecords(HistoricalBitRecordParamsType const& /*unused*/, ::std::uint16_t const& /*unused*/) {}
    // Inline no-op IClient report forwarders (stub).
    void ReportBitCtrlSettings(BitCtrlSettingsType const& /*unused*/) {}
    void ReportBitCtrlStatus(BitCtrlStatusType const& /*unused*/, bool const& /*unused*/) {}
    void ResponseHistoricalRecords(HistoricalBitRecordParamsType const& /*unused*/, BitRecordListType const& /*unused*/, ::std::uint32_t const& /*unused*/) {}



private:
    Client(int domain, std::string svc, IClient& cb);
    int sub_id_ = -1;
};

class Service {
public:
    static std::unique_ptr<Service> create(int domainId, std::string serviceName, IService& cb);
    ~Service();
    // Inline no-op IClient report forwarders (stub).
    void ReportBitCtrlSettings(BitCtrlSettingsType const& /*unused*/) {}
    void ReportBitCtrlStatus(BitCtrlStatusType const& /*unused*/, bool const& /*unused*/) {}
    void ResponseHistoricalRecords(HistoricalBitRecordParamsType const& /*unused*/, BitRecordListType const& /*unused*/, ::std::uint32_t const& /*unused*/) {}
    // Inline no-op IService command forwarders (stub).
    void ConfigAllowTest(bool const& /*unused*/) {}
    void CmdStartTest(::std::string const& /*unused*/) {}
    void CmdCancelTest() {}
    void RequestHistoricalRecords(HistoricalBitRecordParamsType const& /*unused*/, ::std::uint16_t const& /*unused*/) {}



private:
    Service(int domain, std::string svc, IService& cb);
    int sub_id_ = -1;
};

}  // namespace M_BuiltInTestCtrl
