// SPDX-License-Identifier: MIT
// Stub SDK header for M_CameraManager.
#pragma once
#include "M_CameraManager_stub.hpp"   // generated by pipegen (struct types + IClient/IService shells)
#include <memory>
#include <string>

namespace M_CameraManager {

class Client {
public:
    static std::unique_ptr<Client> create(int domainId, std::string serviceName, IClient& cb);
    ~Client();

    // No-op IService command forwarders (stub implementation).
    void CmdDeleteCamera(::std::string const& /*unused*/) {}
    // Inline no-op IService command forwarders (stub).
    void CmdCreateCamera(::std::string const& /*unused*/, ::M_Camera::CameraSettingsType const& /*unused*/) {}
    void CmdUpdateCamera(::std::string const& /*unused*/, ::M_Camera::CameraSettingsType const& /*unused*/) {}
    // Inline no-op IClient report forwarders (stub).
    void ReportCameraSettings(::std::string const& /*unused*/, ::M_Camera::CameraSettingsType const& /*unused*/, bool const& /*unused*/) {}
    void ReportCameraStatus(::std::string const& /*unused*/, ::M_Camera::CameraStatusType const& /*unused*/, bool const& /*unused*/) {}



private:
    Client(int domain, std::string svc, IClient& cb);
    int sub_id_ = -1;
};

class Service {
public:
    static std::unique_ptr<Service> create(int domainId, std::string serviceName, IService& cb);
    ~Service();
    // Inline no-op IClient report forwarders (stub).
    void ReportCameraSettings(::std::string const& /*unused*/, ::M_Camera::CameraSettingsType const& /*unused*/, bool const& /*unused*/) {}
    void ReportCameraStatus(::std::string const& /*unused*/, ::M_Camera::CameraStatusType const& /*unused*/, bool const& /*unused*/) {}
    // Inline no-op IService command forwarders (stub).
    void CmdCreateCamera(::std::string const& /*unused*/, ::M_Camera::CameraSettingsType const& /*unused*/) {}
    void CmdUpdateCamera(::std::string const& /*unused*/, ::M_Camera::CameraSettingsType const& /*unused*/) {}
    void CmdDeleteCamera(::std::string const& /*unused*/) {}



private:
    Service(int domain, std::string svc, IService& cb);
    int sub_id_ = -1;
};

}  // namespace M_CameraManager
