// SPDX-License-Identifier: MIT
// Stub SDK header for M_Camera.
#pragma once
#include "M_Camera_stub.hpp"   // generated by pipegen (struct types + IClient/IService shells)
#include <memory>
#include <string>

namespace M_Camera {

class Client {
public:
    static std::unique_ptr<Client> create(int domainId, std::string serviceName, IClient& cb);
    ~Client();

    // No-op IService command forwarders (stub implementation).
    void ConfigOperationMode(::M_Common::OperationModeType const& /*unused*/) {}
    void ConfigDigitalZoom(bool const& /*unused*/) {}
    void ConfigAutoBrightness(bool const& /*unused*/) {}
    void ConfigAutoContrast(bool const& /*unused*/) {}
    void ConfigEconomyMode(bool const& /*unused*/) {}
    void ConfigCooler(bool const& /*unused*/) {}
    void ConfigAutoGain(bool const& /*unused*/) {}
    void ConfigAutoExposure(bool const& /*unused*/) {}
    void CmdSetRegionOfInterest(::M_Common::PixelRegionType const& /*unused*/) {}
    void ConfigExternalTriggerMode(bool const& /*unused*/) {}
    void ConfigGrabbing(bool const& /*unused*/) {}
    void CmdCalibrateNuc(bool const& /*unused*/) {}
    void ConfigAutoCalibrateNuc(bool const& /*unused*/) {}
    void ConfigInfraredDynamicMode(bool const& /*unused*/) {}
    void ConfigSelectCameraPreset(::std::string const& /*unused*/) {}
    // Inline no-op IService command forwarders (stub).
    void ConfigAutoFocus(AutoFocusKind::Type const& /*unused*/) {}
    void ConfigFocusLevel(::M_Common::PercentType const& /*unused*/) {}
    void CmdSetFocusByStep(::std::int32_t const& /*unused*/) {}
    void ConfigZoomLevel(::M_Common::PercentType const& /*unused*/) {}
    void CmdSetZoomByStep(::std::int32_t const& /*unused*/) {}
    void ConfigPredefinedZoomFov(::std::uint16_t const& /*unused*/) {}
    void CmdSetPredefinedZoomFovByStep(::std::int32_t const& /*unused*/) {}
    void ConfigBrightnessLevel(::M_Common::PercentType const& /*unused*/) {}
    void CmdSetBrightnessByStep(::std::int32_t const& /*unused*/) {}
    void ConfigContrastLevel(::M_Common::PercentType const& /*unused*/) {}
    void CmdSetContrastByStep(::std::int32_t const& /*unused*/) {}
    void ConfigHdrMode(::std::int32_t const& /*unused*/) {}
    void ConfigPolarity(PolarityHotColor::Type const& /*unused*/) {}
    void ConfigGainLevel(::M_Common::PercentType const& /*unused*/) {}
    void CmdSetGainByStep(::std::int32_t const& /*unused*/) {}
    void ConfigExposureTime(::std::uint16_t const& /*unused*/) {}
    void ConfigAperture(::M_Common::ProportionalType const& /*unused*/) {}
    void CmdClearRegionOfInterest() {}
    void ConfigAlphaBlendingLevel(::M_Common::PercentType const& /*unused*/) {}
    void CmdSetFalseColour(bool const& /*unused*/, ::std::string const& /*unused*/) {}
    void CmdStartFocusEngine(ScaleDirection::Type const& /*unused*/) {}
    void CmdStopFocusEngine() {}
    void CmdStartZoomEngine(ScaleDirection::Type const& /*unused*/) {}
    void CmdStopZoomEngine() {}
    void CmdFreezeImage() {}
    // Inline no-op IClient report forwarders (stub).
    void ReportCameraSettings(CameraSettingsType const& /*unused*/) {}
    void ReportCameraStatus(CameraStatusType const& /*unused*/, bool const& /*unused*/) {}
    void EventSafetyCode(SafetyCodeListType const& /*unused*/) {}



private:
    Client(int domain, std::string svc, IClient& cb);
    int sub_id_ = -1;
};

class Service {
public:
    static std::unique_ptr<Service> create(int domainId, std::string serviceName, IService& cb);
    ~Service();
    // Inline no-op IClient report forwarders (stub).
    void ReportCameraSettings(CameraSettingsType const& /*unused*/) {}
    void ReportCameraStatus(CameraStatusType const& /*unused*/, bool const& /*unused*/) {}
    void EventSafetyCode(SafetyCodeListType const& /*unused*/) {}
    // Inline no-op IService command forwarders (stub).
    void ConfigOperationMode(::M_Common::OperationModeType const& /*unused*/) {}
    void ConfigAutoFocus(AutoFocusKind::Type const& /*unused*/) {}
    void ConfigFocusLevel(::M_Common::PercentType const& /*unused*/) {}
    void CmdSetFocusByStep(::std::int32_t const& /*unused*/) {}
    void ConfigDigitalZoom(bool const& /*unused*/) {}
    void ConfigZoomLevel(::M_Common::PercentType const& /*unused*/) {}
    void CmdSetZoomByStep(::std::int32_t const& /*unused*/) {}
    void ConfigPredefinedZoomFov(::std::uint16_t const& /*unused*/) {}
    void CmdSetPredefinedZoomFovByStep(::std::int32_t const& /*unused*/) {}
    void ConfigAutoBrightness(bool const& /*unused*/) {}
    void ConfigBrightnessLevel(::M_Common::PercentType const& /*unused*/) {}
    void CmdSetBrightnessByStep(::std::int32_t const& /*unused*/) {}
    void ConfigAutoContrast(bool const& /*unused*/) {}
    void ConfigContrastLevel(::M_Common::PercentType const& /*unused*/) {}
    void CmdSetContrastByStep(::std::int32_t const& /*unused*/) {}
    void ConfigHdrMode(::std::int32_t const& /*unused*/) {}
    void ConfigPolarity(PolarityHotColor::Type const& /*unused*/) {}
    void ConfigEconomyMode(bool const& /*unused*/) {}
    void ConfigCooler(bool const& /*unused*/) {}
    void ConfigAutoGain(bool const& /*unused*/) {}
    void ConfigGainLevel(::M_Common::PercentType const& /*unused*/) {}
    void CmdSetGainByStep(::std::int32_t const& /*unused*/) {}
    void ConfigExposureTime(::std::uint16_t const& /*unused*/) {}
    void ConfigAutoExposure(bool const& /*unused*/) {}
    void ConfigAperture(::M_Common::ProportionalType const& /*unused*/) {}
    void CmdSetRegionOfInterest(::M_Common::PixelRegionType const& /*unused*/) {}
    void CmdClearRegionOfInterest() {}
    void ConfigExternalTriggerMode(bool const& /*unused*/) {}
    void ConfigGrabbing(bool const& /*unused*/) {}
    void CmdCalibrateNuc(bool const& /*unused*/) {}
    void ConfigAutoCalibrateNuc(bool const& /*unused*/) {}
    void ConfigAlphaBlendingLevel(::M_Common::PercentType const& /*unused*/) {}
    void CmdSetFalseColour(bool const& /*unused*/, ::std::string const& /*unused*/) {}
    void ConfigInfraredDynamicMode(bool const& /*unused*/) {}
    void ConfigSelectCameraPreset(::std::string const& /*unused*/) {}
    void CmdStartFocusEngine(ScaleDirection::Type const& /*unused*/) {}
    void CmdStopFocusEngine() {}
    void CmdStartZoomEngine(ScaleDirection::Type const& /*unused*/) {}
    void CmdStopZoomEngine() {}
    void CmdFreezeImage() {}



private:
    Service(int domain, std::string svc, IService& cb);
    int sub_id_ = -1;
};

}  // namespace M_Camera
