// SPDX-License-Identifier: MIT
// Stub SDK header for M_CoordinateFrame.
#pragma once
#include "M_CoordinateFrame_stub.hpp"   // generated by pipegen (struct types + IClient/IService shells)
#include <memory>
#include <string>

namespace M_CoordinateFrame {

class Client {
public:
    static std::unique_ptr<Client> create(int domainId, std::string serviceName, IClient& cb);
    ~Client();
    // Inline no-op IService command forwarders (stub).
    void NotifyCoordinateTransformation(::std::string const& /*unused*/, ::M_Common::CoordinateTransformationType const& /*unused*/) {}
    void NotifyPosition(::std::string const& /*unused*/, ::M_Common::PositionType const& /*unused*/) {}
    void NotifyAttitude(::std::string const& /*unused*/, ::M_Common::AttitudeType const& /*unused*/) {}
    void NotifyLinearVelocity(::std::string const& /*unused*/, ::M_Common::LinearVelocityType const& /*unused*/) {}
    void NotifyAngularVelocity(::std::string const& /*unused*/, ::M_Common::AngularVelocityType const& /*unused*/) {}
    // Inline no-op IClient report forwarders (stub).
    void ReportCoordinateFrameSettings(CoordinateFrameSettingsType const& /*unused*/) {}
    void ReportCoordinateFrameStatus(CoordinateFrameStatusType const& /*unused*/, bool const& /*unused*/) {}
    void ReportCoordinateTransformations(::std::string const& /*unused*/, ::M_Common::CoordinateTransformationListType const& /*unused*/, bool const& /*unused*/) {}
    void ReportPositions(::std::string const& /*unused*/, ::M_Common::PositionListType const& /*unused*/, bool const& /*unused*/) {}
    void ReportAttitudes(::std::string const& /*unused*/, ::M_Common::AttitudeListType const& /*unused*/, bool const& /*unused*/) {}
    void ReportLinearVelocities(::std::string const& /*unused*/, ::M_Common::LinearVelocityListType const& /*unused*/, bool const& /*unused*/) {}
    void ReportAngularVelocities(::std::string const& /*unused*/, ::M_Common::AngularVelocityListType const& /*unused*/, bool const& /*unused*/) {}
    void ReportLinearAccelerations(::std::string const& /*unused*/, ::M_Common::LinearAccelerationListType const& /*unused*/, bool const& /*unused*/) {}
    void ReportAngularAccelerations(::std::string const& /*unused*/, ::M_Common::AngularAccelerationListType const& /*unused*/, bool const& /*unused*/) {}



private:
    Client(int domain, std::string svc, IClient& cb);
    int sub_id_ = -1;
};

class Service {
public:
    static std::unique_ptr<Service> create(int domainId, std::string serviceName, IService& cb);
    ~Service();
    // Inline no-op IClient report forwarders (stub).
    void ReportCoordinateFrameSettings(CoordinateFrameSettingsType const& /*unused*/) {}
    void ReportCoordinateFrameStatus(CoordinateFrameStatusType const& /*unused*/, bool const& /*unused*/) {}
    void ReportCoordinateTransformations(::std::string const& /*unused*/, ::M_Common::CoordinateTransformationListType const& /*unused*/, bool const& /*unused*/) {}
    void ReportPositions(::std::string const& /*unused*/, ::M_Common::PositionListType const& /*unused*/, bool const& /*unused*/) {}
    void ReportAttitudes(::std::string const& /*unused*/, ::M_Common::AttitudeListType const& /*unused*/, bool const& /*unused*/) {}
    void ReportLinearVelocities(::std::string const& /*unused*/, ::M_Common::LinearVelocityListType const& /*unused*/, bool const& /*unused*/) {}
    void ReportAngularVelocities(::std::string const& /*unused*/, ::M_Common::AngularVelocityListType const& /*unused*/, bool const& /*unused*/) {}
    void ReportLinearAccelerations(::std::string const& /*unused*/, ::M_Common::LinearAccelerationListType const& /*unused*/, bool const& /*unused*/) {}
    void ReportAngularAccelerations(::std::string const& /*unused*/, ::M_Common::AngularAccelerationListType const& /*unused*/, bool const& /*unused*/) {}
    // Inline no-op IService command forwarders (stub).
    void NotifyCoordinateTransformation(::std::string const& /*unused*/, ::M_Common::CoordinateTransformationType const& /*unused*/) {}
    void NotifyPosition(::std::string const& /*unused*/, ::M_Common::PositionType const& /*unused*/) {}
    void NotifyAttitude(::std::string const& /*unused*/, ::M_Common::AttitudeType const& /*unused*/) {}
    void NotifyLinearVelocity(::std::string const& /*unused*/, ::M_Common::LinearVelocityType const& /*unused*/) {}
    void NotifyAngularVelocity(::std::string const& /*unused*/, ::M_Common::AngularVelocityType const& /*unused*/) {}



private:
    Service(int domain, std::string svc, IService& cb);
    int sub_id_ = -1;
};

}  // namespace M_CoordinateFrame
