// SPDX-License-Identifier: MIT
// Stub SDK header for M_Device.
#pragma once
#include "M_Device_stub.hpp"   // generated by pipegen (struct types + IClient/IService shells)
#include <memory>
#include <string>

namespace M_Device {

class Client {
public:
    static std::unique_ptr<Client> create(int domainId, std::string serviceName, IClient& cb);
    ~Client();

    // No-op IService command forwarders (stub implementation).
    void CmdEnableDevice(bool const& /*unused*/) {}
    void CmdSetDeviceMode(::M_Common::OperationModeType const& /*unused*/) {}
    void RequestValue(::std::string const& /*unused*/) {}
    // Inline no-op IService command forwarders (stub).
    void CmdIsDeviceAlive() {}
    void CmdShutdownDevice() {}
    void CmdRestartDevice() {}
    void CmdSetValue(::std::string const& /*unused*/, ::M_Common::PropertyType const& /*unused*/) {}
    void CmdSetValueIncrementally(::std::string const& /*unused*/, ::M_Common::PropertyType const& /*unused*/) {}
    // Inline no-op IClient report forwarders (stub).
    void ReportDeviceSettings(DeviceSettingsType const& /*unused*/) {}
    void ReportDeviceStatus(DeviceStatusType const& /*unused*/, bool const& /*unused*/) {}
    void ReportValue(::std::string const& /*unused*/, ::M_Common::PropertyType const& /*unused*/, bool const& /*unused*/) {}
    void ResponseValue(::std::string const& /*unused*/, ::M_Common::PropertyType const& /*unused*/) {}



private:
    Client(int domain, std::string svc, IClient& cb);
    int sub_id_ = -1;
};

class Service {
public:
    static std::unique_ptr<Service> create(int domainId, std::string serviceName, IService& cb);
    ~Service();
    // Inline no-op IClient report forwarders (stub).
    void ReportDeviceSettings(DeviceSettingsType const& /*unused*/) {}
    void ReportDeviceStatus(DeviceStatusType const& /*unused*/, bool const& /*unused*/) {}
    void ReportValue(::std::string const& /*unused*/, ::M_Common::PropertyType const& /*unused*/, bool const& /*unused*/) {}
    void ResponseValue(::std::string const& /*unused*/, ::M_Common::PropertyType const& /*unused*/) {}
    // Inline no-op IService command forwarders (stub).
    void CmdIsDeviceAlive() {}
    void CmdEnableDevice(bool const& /*unused*/) {}
    void CmdShutdownDevice() {}
    void CmdRestartDevice() {}
    void CmdSetDeviceMode(::M_Common::OperationModeType const& /*unused*/) {}
    void CmdSetValue(::std::string const& /*unused*/, ::M_Common::PropertyType const& /*unused*/) {}
    void CmdSetValueIncrementally(::std::string const& /*unused*/, ::M_Common::PropertyType const& /*unused*/) {}
    void RequestValue(::std::string const& /*unused*/) {}



private:
    Service(int domain, std::string svc, IService& cb);
    int sub_id_ = -1;
};

}  // namespace M_Device
