// SPDX-License-Identifier: MIT
// Stub SDK header for M_Dialogue.
#pragma once
#include "M_Dialogue_stub.hpp"   // generated by pipegen (struct types + IClient/IService shells)
#include <memory>
#include <string>

namespace M_Dialogue {

class Client {
public:
    static std::unique_ptr<Client> create(int domainId, std::string serviceName, IClient& cb);
    ~Client();
    // Inline no-op IService command forwarders (stub).
    void ConfigLogLevel(DialogueCategoryKind::Type const& /*unused*/) {}
    void CmdSelectInputChoice(::M_Common::ObjectIdType const& /*unused*/, ::M_Common::StringListType const& /*unused*/) {}
    void NotifyTextMessage(::std::string const& /*unused*/, DialogueCategoryOptionalType const& /*unused*/) {}
    // Inline no-op IClient report forwarders (stub).
    void EventTextMessage(::std::string const& /*unused*/, DialogueCategoryOptionalType const& /*unused*/) {}
    void ReportInputChoice(::M_Common::ObjectIdType const& /*unused*/, InputChoiceType const& /*unused*/, bool const& /*unused*/) {}



private:
    Client(int domain, std::string svc, IClient& cb);
    int sub_id_ = -1;
};

class Service {
public:
    static std::unique_ptr<Service> create(int domainId, std::string serviceName, IService& cb);
    ~Service();
    // Inline no-op IClient report forwarders (stub).
    void EventTextMessage(::std::string const& /*unused*/, DialogueCategoryOptionalType const& /*unused*/) {}
    void ReportInputChoice(::M_Common::ObjectIdType const& /*unused*/, InputChoiceType const& /*unused*/, bool const& /*unused*/) {}
    // Inline no-op IService command forwarders (stub).
    void ConfigLogLevel(DialogueCategoryKind::Type const& /*unused*/) {}
    void CmdSelectInputChoice(::M_Common::ObjectIdType const& /*unused*/, ::M_Common::StringListType const& /*unused*/) {}
    void NotifyTextMessage(::std::string const& /*unused*/, DialogueCategoryOptionalType const& /*unused*/) {}



private:
    Service(int domain, std::string svc, IService& cb);
    int sub_id_ = -1;
};

}  // namespace M_Dialogue
