// SPDX-License-Identifier: MIT
// Stub SDK header for M_FileTransfer.
#pragma once
#include "M_FileTransfer_stub.hpp"   // generated by pipegen (struct types + IClient/IService shells)
#include <memory>
#include <string>

namespace M_FileTransfer {

class Client {
public:
    static std::unique_ptr<Client> create(int domainId, std::string serviceName, IClient& cb);
    ~Client();

    // No-op IService command forwarders (stub implementation).
    void CmdCancelFileTransfer(::std::string const& /*unused*/) {}
    void CmdPauseFileTransfer(::std::string const& /*unused*/) {}
    void CmdResumeFileTransfer(::std::string const& /*unused*/) {}
    // Inline no-op IService command forwarders (stub).
    void CmdStartFileTransfer(::std::string const& /*unused*/, FileTransferInfoType const& /*unused*/) {}
    // Inline no-op IClient report forwarders (stub).
    void ReportFileTransferStatus(::std::string const& /*unused*/, FileTransferStatusType const& /*unused*/, FileTransferInfoOptionalType const& /*unused*/, bool const& /*unused*/) {}



private:
    Client(int domain, std::string svc, IClient& cb);
    int sub_id_ = -1;
};

class Service {
public:
    static std::unique_ptr<Service> create(int domainId, std::string serviceName, IService& cb);
    ~Service();
    // Inline no-op IClient report forwarders (stub).
    void ReportFileTransferStatus(::std::string const& /*unused*/, FileTransferStatusType const& /*unused*/, FileTransferInfoOptionalType const& /*unused*/, bool const& /*unused*/) {}
    // Inline no-op IService command forwarders (stub).
    void CmdStartFileTransfer(::std::string const& /*unused*/, FileTransferInfoType const& /*unused*/) {}
    void CmdCancelFileTransfer(::std::string const& /*unused*/) {}
    void CmdPauseFileTransfer(::std::string const& /*unused*/) {}
    void CmdResumeFileTransfer(::std::string const& /*unused*/) {}



private:
    Service(int domain, std::string svc, IService& cb);
    int sub_id_ = -1;
};

}  // namespace M_FileTransfer
