// SPDX-License-Identifier: MIT
// Stub SDK header for M_GenericInputOutput.
#pragma once
#include "M_GenericInputOutput_stub.hpp"   // generated by pipegen (struct types + IClient/IService shells)
#include <memory>
#include <string>

namespace M_GenericInputOutput {

class Client {
public:
    static std::unique_ptr<Client> create(int domainId, std::string serviceName, IClient& cb);
    ~Client();

    // No-op IService command forwarders (stub implementation).
    void CmdWriteData(::M_GenericInputOutput::InputOutputData const& /*unused*/) {}
    void CmdReadRegister(::std::string const& /*unused*/) {}
    // Inline no-op IService command forwarders (stub).
    void ConfigInterfaceProperties(::std::string const& /*unused*/, InputOutputConfiguration const& /*unused*/, bool const& /*unused*/) {}
    void CmdRead() {}
    void CmdWriteRegister(::std::string const& /*unused*/, ::M_Common::PropertyType const& /*unused*/) {}
    void CmdStopWriting() {}
    // Inline no-op IClient report forwarders (stub).
    void ReportInputOutputSettings(InputOutputSettings const& /*unused*/) {}
    void ReportInputOutputStatus(InputOutputStatus const& /*unused*/, bool const& /*unused*/) {}
    void ReportRegister(::std::string const& /*unused*/, ::M_Common::PropertyType const& /*unused*/, bool const& /*unused*/) {}
    void ReportActiveErrors(::M_Common::StringListType const& /*unused*/, bool const& /*unused*/) {}
    void EventDataReceived(InputOutputData const& /*unused*/) {}



private:
    Client(int domain, std::string svc, IClient& cb);
    int sub_id_ = -1;
};

class Service {
public:
    static std::unique_ptr<Service> create(int domainId, std::string serviceName, IService& cb);
    ~Service();
    // Inline no-op IClient report forwarders (stub).
    void ReportInputOutputSettings(InputOutputSettings const& /*unused*/) {}
    void ReportInputOutputStatus(InputOutputStatus const& /*unused*/, bool const& /*unused*/) {}
    void ReportRegister(::std::string const& /*unused*/, ::M_Common::PropertyType const& /*unused*/, bool const& /*unused*/) {}
    void ReportActiveErrors(::M_Common::StringListType const& /*unused*/, bool const& /*unused*/) {}
    void EventDataReceived(InputOutputData const& /*unused*/) {}
    // Inline no-op IService command forwarders (stub).
    void ConfigInterfaceProperties(::std::string const& /*unused*/, InputOutputConfiguration const& /*unused*/, bool const& /*unused*/) {}
    void CmdRead() {}
    void CmdWriteData(InputOutputData const& /*unused*/) {}
    void CmdReadRegister(::std::string const& /*unused*/) {}
    void CmdWriteRegister(::std::string const& /*unused*/, ::M_Common::PropertyType const& /*unused*/) {}
    void CmdStopWriting() {}



private:
    Service(int domain, std::string svc, IService& cb);
    int sub_id_ = -1;
};

}  // namespace M_GenericInputOutput
