// SPDX-License-Identifier: MIT
// Stub SDK header for M_HidCoordInput.
#pragma once
#include "M_HidCoordInput_stub.hpp"   // generated by pipegen (struct types + IClient/IService shells)
#include <memory>
#include <string>

namespace M_HidCoordInput {

class Client {
public:
    static std::unique_ptr<Client> create(int domainId, std::string serviceName, IClient& cb);
    ~Client();
    // Inline no-op IService command forwarders (stub).
    void CmdIsCoordInputAlive() {}
    // Inline no-op IClient report forwarders (stub).
    void ReportCoordInputSettings(CoordInputSettingsType const& /*unused*/) {}
    void EventClick(::M_Common::PixelPoint2DType const& /*unused*/, bool const& /*unused*/) {}
    void ReportCursorPosition(::M_Common::PixelPoint2DType const& /*unused*/, bool const& /*unused*/) {}



private:
    Client(int domain, std::string svc, IClient& cb);
    int sub_id_ = -1;
};

class Service {
public:
    static std::unique_ptr<Service> create(int domainId, std::string serviceName, IService& cb);
    ~Service();
    // Inline no-op IClient report forwarders (stub).
    void ReportCoordInputSettings(CoordInputSettingsType const& /*unused*/) {}
    void EventClick(::M_Common::PixelPoint2DType const& /*unused*/, bool const& /*unused*/) {}
    void ReportCursorPosition(::M_Common::PixelPoint2DType const& /*unused*/, bool const& /*unused*/) {}
    // Inline no-op IService command forwarders (stub).
    void CmdIsCoordInputAlive() {}



private:
    Service(int domain, std::string svc, IService& cb);
    int sub_id_ = -1;
};

}  // namespace M_HidCoordInput
