// SPDX-License-Identifier: MIT
// Stub SDK header for M_HidDisplay.
#pragma once
#include "M_HidDisplay_stub.hpp"   // generated by pipegen (struct types + IClient/IService shells)
#include <memory>
#include <string>

namespace M_HidDisplay {

class Client {
public:
    static std::unique_ptr<Client> create(int domainId, std::string serviceName, IClient& cb);
    ~Client();

    // No-op IService command forwarders (stub implementation).
    void ConfigBlackoutMode(bool const& /*unused*/) {}
    // Inline no-op IService command forwarders (stub).
    void ConfigAxisLabel(::std::uint32_t const& /*unused*/, ::std::string const& /*unused*/, ::M_Common::ImageType const& /*unused*/, ::std::string const& /*unused*/, ::M_Common::ImageType const& /*unused*/, bool const& /*unused*/) {}
    void ConfigStatusLed(::std::uint32_t const& /*unused*/, LedLightModeType const& /*unused*/, bool const& /*unused*/) {}
    void ConfigBackgroundIllumination(::M_Common::PercentType const& /*unused*/) {}
    void ConfigButtonLabel(::std::uint32_t const& /*unused*/, ::std::string const& /*unused*/, ::M_Common::ImageType const& /*unused*/, bool const& /*unused*/, bool const& /*unused*/, bool const& /*unused*/) {}
    void ConfigValueInput(::std::uint32_t const& /*unused*/, ::std::string const& /*unused*/, bool const& /*unused*/, ::M_Common::PropertyOptionalType const& /*unused*/, ::M_Common::PropertyOptionalType const& /*unused*/, ::M_Common::PropertyOptionalType const& /*unused*/, ::M_Common::PropertyOptionalType const& /*unused*/, ::M_Common::PropertyListType const& /*unused*/, bool const& /*unused*/) {}
    void ConfigMenuLabel(::std::uint32_t const& /*unused*/, ::std::string const& /*unused*/, bool const& /*unused*/, bool const& /*unused*/) {}
    void CmdSelectButton(::std::uint32_t const& /*unused*/, bool const& /*unused*/) {}
    // Inline no-op IClient report forwarders (stub).
    void ReportHidInfo(HidInfoType const& /*unused*/) {}



private:
    Client(int domain, std::string svc, IClient& cb);
    int sub_id_ = -1;
};

class Service {
public:
    static std::unique_ptr<Service> create(int domainId, std::string serviceName, IService& cb);
    ~Service();
    // Inline no-op IClient report forwarders (stub).
    void ReportHidInfo(HidInfoType const& /*unused*/) {}
    // Inline no-op IService command forwarders (stub).
    void ConfigAxisLabel(::std::uint32_t const& /*unused*/, ::std::string const& /*unused*/, ::M_Common::ImageType const& /*unused*/, ::std::string const& /*unused*/, ::M_Common::ImageType const& /*unused*/, bool const& /*unused*/) {}
    void ConfigStatusLed(::std::uint32_t const& /*unused*/, LedLightModeType const& /*unused*/, bool const& /*unused*/) {}
    void ConfigBackgroundIllumination(::M_Common::PercentType const& /*unused*/) {}
    void ConfigBlackoutMode(bool const& /*unused*/) {}
    void ConfigButtonLabel(::std::uint32_t const& /*unused*/, ::std::string const& /*unused*/, ::M_Common::ImageType const& /*unused*/, bool const& /*unused*/, bool const& /*unused*/, bool const& /*unused*/) {}
    void ConfigValueInput(::std::uint32_t const& /*unused*/, ::std::string const& /*unused*/, bool const& /*unused*/, ::M_Common::PropertyOptionalType const& /*unused*/, ::M_Common::PropertyOptionalType const& /*unused*/, ::M_Common::PropertyOptionalType const& /*unused*/, ::M_Common::PropertyOptionalType const& /*unused*/, ::M_Common::PropertyListType const& /*unused*/, bool const& /*unused*/) {}
    void ConfigMenuLabel(::std::uint32_t const& /*unused*/, ::std::string const& /*unused*/, bool const& /*unused*/, bool const& /*unused*/) {}
    void CmdSelectButton(::std::uint32_t const& /*unused*/, bool const& /*unused*/) {}



private:
    Service(int domain, std::string svc, IService& cb);
    int sub_id_ = -1;
};

}  // namespace M_HidDisplay
