// SPDX-License-Identifier: MIT
// Stub SDK header for M_HidManager.
#pragma once
#include "M_HidManager_stub.hpp"   // generated by pipegen (struct types + IClient/IService shells)
#include <memory>
#include <string>

namespace M_HidManager {

class Client {
public:
    static std::unique_ptr<Client> create(int domainId, std::string serviceName, IClient& cb);
    ~Client();
    // Inline no-op IService command forwarders (stub).
    void CmdIsHidManagerAlive() {}
    void ConfigHidAssignment(::std::string const& /*unused*/, RequestedAxisListType const& /*unused*/, RequestedValueInputListType const& /*unused*/, RequestedButtonListType const& /*unused*/, RequestedMenuListType const& /*unused*/, bool const& /*unused*/) {}
    // Inline no-op IClient report forwarders (stub).
    void ReportHidAssignment(::std::string const& /*unused*/, AssignedAxisListType const& /*unused*/, AssignedValueInputListType const& /*unused*/, AssignedButtonListType const& /*unused*/, AssignedMenuListType const& /*unused*/, bool const& /*unused*/) {}



private:
    Client(int domain, std::string svc, IClient& cb);
    int sub_id_ = -1;
};

class Service {
public:
    static std::unique_ptr<Service> create(int domainId, std::string serviceName, IService& cb);
    ~Service();
    // Inline no-op IClient report forwarders (stub).
    void ReportHidAssignment(::std::string const& /*unused*/, AssignedAxisListType const& /*unused*/, AssignedValueInputListType const& /*unused*/, AssignedButtonListType const& /*unused*/, AssignedMenuListType const& /*unused*/, bool const& /*unused*/) {}
    // Inline no-op IService command forwarders (stub).
    void CmdIsHidManagerAlive() {}
    void ConfigHidAssignment(::std::string const& /*unused*/, RequestedAxisListType const& /*unused*/, RequestedValueInputListType const& /*unused*/, RequestedButtonListType const& /*unused*/, RequestedMenuListType const& /*unused*/, bool const& /*unused*/) {}



private:
    Service(int domain, std::string svc, IService& cb);
    int sub_id_ = -1;
};

}  // namespace M_HidManager
