// SPDX-License-Identifier: MIT
// Stub SDK header for M_HidJoystick.
#pragma once
#include "M_HidJoystick_stub.hpp"   // generated by pipegen (struct types + IClient/IService shells)
#include <memory>
#include <string>

namespace M_HidJoystick {

class Client {
public:
    static std::unique_ptr<Client> create(int domainId, std::string serviceName, IClient& cb);
    ~Client();
    // Inline no-op IService command forwarders (stub).
    void CmdIsJoystickAlive() {}
    void ConfigJoystickCurve(::std::uint32_t const& /*unused*/, ::std::string const& /*unused*/, bool const& /*unused*/) {}
    // Inline no-op IClient report forwarders (stub).
    void EventButton(::std::uint32_t const& /*unused*/, ::std::string const& /*unused*/, bool const& /*unused*/) {}
    void EventIncrement(::std::uint32_t const& /*unused*/, ::std::int32_t const& /*unused*/) {}
    void ReportJoystickSettings(JoystickSettingsType const& /*unused*/) {}
    void ReportAxis(::std::uint32_t const& /*unused*/, double const& /*unused*/, bool const& /*unused*/) {}
    void ReportInputValue(::std::uint32_t const& /*unused*/, ::M_Common::PropertyType const& /*unused*/, bool const& /*unused*/) {}
    void ReportMenuStatus(::std::uint32_t const& /*unused*/, bool const& /*unused*/, bool const& /*unused*/) {}
    void ReportJoystickCurve(::std::uint32_t const& /*unused*/, ::std::string const& /*unused*/, bool const& /*unused*/) {}



private:
    Client(int domain, std::string svc, IClient& cb);
    int sub_id_ = -1;
};

class Service {
public:
    static std::unique_ptr<Service> create(int domainId, std::string serviceName, IService& cb);
    ~Service();
    // Inline no-op IClient report forwarders (stub).
    void EventButton(::std::uint32_t const& /*unused*/, ::std::string const& /*unused*/, bool const& /*unused*/) {}
    void EventIncrement(::std::uint32_t const& /*unused*/, ::std::int32_t const& /*unused*/) {}
    void ReportJoystickSettings(JoystickSettingsType const& /*unused*/) {}
    void ReportAxis(::std::uint32_t const& /*unused*/, double const& /*unused*/, bool const& /*unused*/) {}
    void ReportInputValue(::std::uint32_t const& /*unused*/, ::M_Common::PropertyType const& /*unused*/, bool const& /*unused*/) {}
    void ReportMenuStatus(::std::uint32_t const& /*unused*/, bool const& /*unused*/, bool const& /*unused*/) {}
    void ReportJoystickCurve(::std::uint32_t const& /*unused*/, ::std::string const& /*unused*/, bool const& /*unused*/) {}
    // Inline no-op IService command forwarders (stub).
    void CmdIsJoystickAlive() {}
    void ConfigJoystickCurve(::std::uint32_t const& /*unused*/, ::std::string const& /*unused*/, bool const& /*unused*/) {}



private:
    Service(int domain, std::string svc, IService& cb);
    int sub_id_ = -1;
};

}  // namespace M_HidJoystick
