// SPDX-License-Identifier: MIT
// Stub SDK header for M_HmiAppCtrl.
#pragma once
#include "M_HmiAppCtrl_stub.hpp"   // generated by pipegen (struct types + IClient/IService shells)
#include <memory>
#include <string>

namespace M_HmiAppCtrl {

class Client {
public:
    static std::unique_ptr<Client> create(int domainId, std::string serviceName, IClient& cb);
    ~Client();

    // No-op IService command forwarders (stub implementation).
    void CmdActivateView(::std::string const& /*unused*/) {}
    void CmdRunApp(::std::string const& /*unused*/) {}
    void CmdSwitchToApp(::std::string const& /*unused*/) {}
    void CmdTerminateApp(::std::string const& /*unused*/) {}
    void CmdRestartApp(::std::string const& /*unused*/) {}
    void CmdUninstallApp(::std::string const& /*unused*/) {}
    void CmdUnregisterApp(::std::string const& /*unused*/) {}
    // Inline no-op IService command forwarders (stub).
    void ConfigView(::std::string const& /*unused*/, ViewDescriptionType const& /*unused*/, bool const& /*unused*/) {}
    void CmdRegisterApp(::std::string const& /*unused*/, ApplicationDescriptionType const& /*unused*/) {}
    void CmdInstallApp(::std::string const& /*unused*/, ApplicationDescriptionType const& /*unused*/) {}
    void CmdActivateContext(::std::string const& /*unused*/, bool const& /*unused*/) {}
    // Inline no-op IClient report forwarders (stub).
    void ReportView(::std::string const& /*unused*/, ViewDescriptionType const& /*unused*/, bool const& /*unused*/) {}
    void ReportManagedApps(ApplicationDescriptionListType const& /*unused*/) {}
    void ReportAppState(::std::string const& /*unused*/, ApplicationStateType const& /*unused*/, bool const& /*unused*/) {}
    void ReportActiveContexts(::M_Common::StringListType const& /*unused*/) {}



private:
    Client(int domain, std::string svc, IClient& cb);
    int sub_id_ = -1;
};

class Service {
public:
    static std::unique_ptr<Service> create(int domainId, std::string serviceName, IService& cb);
    ~Service();
    // Inline no-op IClient report forwarders (stub).
    void ReportView(::std::string const& /*unused*/, ViewDescriptionType const& /*unused*/, bool const& /*unused*/) {}
    void ReportManagedApps(ApplicationDescriptionListType const& /*unused*/) {}
    void ReportAppState(::std::string const& /*unused*/, ApplicationStateType const& /*unused*/, bool const& /*unused*/) {}
    void ReportActiveContexts(::M_Common::StringListType const& /*unused*/) {}
    // Inline no-op IService command forwarders (stub).
    void ConfigView(::std::string const& /*unused*/, ViewDescriptionType const& /*unused*/, bool const& /*unused*/) {}
    void CmdActivateView(::std::string const& /*unused*/) {}
    void CmdRegisterApp(::std::string const& /*unused*/, ApplicationDescriptionType const& /*unused*/) {}
    void CmdInstallApp(::std::string const& /*unused*/, ApplicationDescriptionType const& /*unused*/) {}
    void CmdRunApp(::std::string const& /*unused*/) {}
    void CmdSwitchToApp(::std::string const& /*unused*/) {}
    void CmdTerminateApp(::std::string const& /*unused*/) {}
    void CmdRestartApp(::std::string const& /*unused*/) {}
    void CmdUninstallApp(::std::string const& /*unused*/) {}
    void CmdUnregisterApp(::std::string const& /*unused*/) {}
    void CmdActivateContext(::std::string const& /*unused*/, bool const& /*unused*/) {}



private:
    Service(int domain, std::string svc, IService& cb);
    int sub_id_ = -1;
};

}  // namespace M_HmiAppCtrl
