// SPDX-License-Identifier: MIT
// Stub SDK header for M_ImageProcessing.
#pragma once
#include "M_ImageProcessing_stub.hpp"   // generated by pipegen (struct types + IClient/IService shells)
#include <memory>
#include <string>

namespace M_ImageProcessing {

class Client {
public:
    static std::unique_ptr<Client> create(int domainId, std::string serviceName, IClient& cb);
    ~Client();

    // No-op IService command forwarders (stub implementation).
    void ConfigFrameDrop(::M_ImageProcessing::FrameDropType const& /*unused*/) {}
    void CmdSetRegion(::M_Common::ImageRegionType const& /*unused*/) {}
    void CmdScale(::M_Common::PixelRectSizeType const& /*unused*/) {}
    // Inline no-op IService command forwarders (stub).
    void ConfigInterpolation(InterpolationKind::Type const& /*unused*/) {}
    void ConfigBitrate(::M_Common::BitrateKiloBitsPerSecType const& /*unused*/) {}
    void CmdRotate(::M_Common::AngleDegreesType const& /*unused*/) {}
    void CmdFlip(FlipDirectionKind::Type const& /*unused*/) {}
    // Inline no-op IClient report forwarders (stub).
    void ReportImageProcessingSettings(ImageProcessingSettingsType const& /*unused*/) {}
    void ReportImageProcessingStatus(ImageProcessingStatusType const& /*unused*/, bool const& /*unused*/) {}



private:
    Client(int domain, std::string svc, IClient& cb);
    int sub_id_ = -1;
};

class Service {
public:
    static std::unique_ptr<Service> create(int domainId, std::string serviceName, IService& cb);
    ~Service();
    // Inline no-op IClient report forwarders (stub).
    void ReportImageProcessingSettings(ImageProcessingSettingsType const& /*unused*/) {}
    void ReportImageProcessingStatus(ImageProcessingStatusType const& /*unused*/, bool const& /*unused*/) {}
    // Inline no-op IService command forwarders (stub).
    void ConfigInterpolation(InterpolationKind::Type const& /*unused*/) {}
    void ConfigFrameDrop(FrameDropType const& /*unused*/) {}
    void ConfigBitrate(::M_Common::BitrateKiloBitsPerSecType const& /*unused*/) {}
    void CmdSetRegion(::M_Common::ImageRegionType const& /*unused*/) {}
    void CmdScale(::M_Common::PixelRectSizeType const& /*unused*/) {}
    void CmdRotate(::M_Common::AngleDegreesType const& /*unused*/) {}
    void CmdFlip(FlipDirectionKind::Type const& /*unused*/) {}



private:
    Service(int domain, std::string svc, IService& cb);
    int sub_id_ = -1;
};

}  // namespace M_ImageProcessing
