// SPDX-License-Identifier: MIT
// Stub SDK header for M_ImageComposer.
#pragma once
#include "M_ImageComposer_stub.hpp"   // generated by pipegen (struct types + IClient/IService shells)
#include <memory>
#include <string>

namespace M_ImageComposer {

class Client {
public:
    static std::unique_ptr<Client> create(int domainId, std::string serviceName, IClient& cb);
    ~Client();
    // Inline no-op IService command forwarders (stub).
    void ConfigViewports(ViewportListType const& /*unused*/) {}
    // Inline no-op IClient report forwarders (stub).
    void ReportImageComposerSettings(ImageComposerSettingsType const& /*unused*/) {}
    void ReportImageComposerChannelStatus(::std::string const& /*unused*/, ImageComposerChannelStatusType const& /*unused*/, bool const& /*unused*/) {}
    void ReportViewports(ViewportListType const& /*unused*/) {}



private:
    Client(int domain, std::string svc, IClient& cb);
    int sub_id_ = -1;
};

class Service {
public:
    static std::unique_ptr<Service> create(int domainId, std::string serviceName, IService& cb);
    ~Service();
    // Inline no-op IClient report forwarders (stub).
    void ReportImageComposerSettings(ImageComposerSettingsType const& /*unused*/) {}
    void ReportImageComposerChannelStatus(::std::string const& /*unused*/, ImageComposerChannelStatusType const& /*unused*/, bool const& /*unused*/) {}
    void ReportViewports(ViewportListType const& /*unused*/) {}
    // Inline no-op IService command forwarders (stub).
    void ConfigViewports(ViewportListType const& /*unused*/) {}



private:
    Service(int domain, std::string svc, IService& cb);
    int sub_id_ = -1;
};

}  // namespace M_ImageComposer
