// SPDX-License-Identifier: MIT
// Stub SDK header for M_KinematicChain.
#pragma once
#include "M_KinematicChain_stub.hpp"   // generated by pipegen (struct types + IClient/IService shells)
#include <memory>
#include <string>

namespace M_KinematicChain {

class Client {
public:
    static std::unique_ptr<Client> create(int domainId, std::string serviceName, IClient& cb);
    ~Client();

    // No-op IService command forwarders (stub implementation).
    void CmdDeleteStoredAxisRotations(::std::string const& /*unused*/) {}
    void CmdApplyStoredAxisRotation(::std::string const& /*unused*/) {}
    // Inline no-op IService command forwarders (stub).
    void ConfigAxisRotationConstraints(AxisRotationConstraintsListType const& /*unused*/) {}
    void NotifyAxisRotations(::std::string const& /*unused*/, AxisRotationListType const& /*unused*/) {}
    void ConfigStoreAxisRotations(::std::string const& /*unused*/, AxisRotationListType const& /*unused*/, bool const& /*unused*/) {}
    // Inline no-op IClient report forwarders (stub).
    void ReportKinematicChainSettings(KinematicChainSettingsType const& /*unused*/) {}
    void ReportKinematicChainStatus(KinematicChainStatusType const& /*unused*/, bool const& /*unused*/) {}
    void ReportAxisRotationConstraints(AxisRotationConstraintsListType const& /*unused*/) {}
    void ReportAxisRotations(AxisRotationListType const& /*unused*/) {}



private:
    Client(int domain, std::string svc, IClient& cb);
    int sub_id_ = -1;
};

class Service {
public:
    static std::unique_ptr<Service> create(int domainId, std::string serviceName, IService& cb);
    ~Service();
    // Inline no-op IClient report forwarders (stub).
    void ReportKinematicChainSettings(KinematicChainSettingsType const& /*unused*/) {}
    void ReportKinematicChainStatus(KinematicChainStatusType const& /*unused*/, bool const& /*unused*/) {}
    void ReportAxisRotationConstraints(AxisRotationConstraintsListType const& /*unused*/) {}
    void ReportAxisRotations(AxisRotationListType const& /*unused*/) {}
    // Inline no-op IService command forwarders (stub).
    void ConfigAxisRotationConstraints(AxisRotationConstraintsListType const& /*unused*/) {}
    void NotifyAxisRotations(::std::string const& /*unused*/, AxisRotationListType const& /*unused*/) {}
    void ConfigStoreAxisRotations(::std::string const& /*unused*/, AxisRotationListType const& /*unused*/, bool const& /*unused*/) {}
    void CmdDeleteStoredAxisRotations(::std::string const& /*unused*/) {}
    void CmdApplyStoredAxisRotation(::std::string const& /*unused*/) {}



private:
    Service(int domain, std::string svc, IService& cb);
    int sub_id_ = -1;
};

}  // namespace M_KinematicChain
