// SPDX-License-Identifier: MIT
// Stub SDK header for M_LaserRangeFinder.
#pragma once
#include "M_LaserRangeFinder_stub.hpp"   // generated by pipegen (struct types + IClient/IService shells)
#include <memory>
#include <string>

namespace M_LaserRangeFinder {

class Client {
public:
    static std::unique_ptr<Client> create(int domainId, std::string serviceName, IClient& cb);
    ~Client();

    // No-op IService command forwarders (stub implementation).
    void CmdMultiFireLaser(bool const& /*unused*/) {}
    // Inline no-op IService command forwarders (stub).
    void CmdSingleFireLaser() {}
    void ConfigSetFirstOrLastMeasurement(FirstOrLast::Type const& /*unused*/) {}
    void ConfigSetUserRange(::M_Common::DistanceMetersOptionalType const& /*unused*/, ::M_Common::DistanceMetersOptionalType const& /*unused*/) {}
    void ConfigInhibitLaserFiring(::M_Common::ObjectIdType const& /*unused*/, bool const& /*unused*/) {}
    void ConfigMultiFireFrequency(::M_Common::FrequencyHertzType const& /*unused*/) {}
    // Inline no-op IClient report forwarders (stub).
    void ReportLrfSettings(LrfSettingsType const& /*unused*/) {}
    void ReportLrfStatus(LrfStatusType const& /*unused*/, bool const& /*unused*/) {}



private:
    Client(int domain, std::string svc, IClient& cb);
    int sub_id_ = -1;
};

class Service {
public:
    static std::unique_ptr<Service> create(int domainId, std::string serviceName, IService& cb);
    ~Service();
    // Inline no-op IClient report forwarders (stub).
    void ReportLrfSettings(LrfSettingsType const& /*unused*/) {}
    void ReportLrfStatus(LrfStatusType const& /*unused*/, bool const& /*unused*/) {}
    // Inline no-op IService command forwarders (stub).
    void CmdMultiFireLaser(bool const& /*unused*/) {}
    void CmdSingleFireLaser() {}
    void ConfigSetFirstOrLastMeasurement(FirstOrLast::Type const& /*unused*/) {}
    void ConfigSetUserRange(::M_Common::DistanceMetersOptionalType const& /*unused*/, ::M_Common::DistanceMetersOptionalType const& /*unused*/) {}
    void ConfigInhibitLaserFiring(::M_Common::ObjectIdType const& /*unused*/, bool const& /*unused*/) {}
    void ConfigMultiFireFrequency(::M_Common::FrequencyHertzType const& /*unused*/) {}



private:
    Service(int domain, std::string svc, IService& cb);
    int sub_id_ = -1;
};

}  // namespace M_LaserRangeFinder
