// SPDX-License-Identifier: MIT
// Stub SDK header for M_Logging.
#pragma once
#include "M_Logging_stub.hpp"   // generated by pipegen (struct types + IClient/IService shells)
#include <memory>
#include <string>

namespace M_Logging {

class Client {
public:
    static std::unique_ptr<Client> create(int domainId, std::string serviceName, IClient& cb);
    ~Client();

    // No-op IService command forwarders (stub implementation).
    void CmdSetLogSettings(::M_Logging::LogSettingsType const& /*unused*/) {}
    void RequestLogMessages(::M_Logging::LogMessageRequestType const& /*unused*/) {}
    // Inline no-op IClient report forwarders (stub).
    void EventLogMessages(LogMessageListType const& /*unused*/) {}
    void ReportLogSettings(LogSettingsType const& /*unused*/, bool const& /*unused*/) {}
    void ResponseLogMessages(LogMessageRequestType const& /*unused*/, LogMessageListType const& /*unused*/) {}


private:
    Client(int domain, std::string svc, IClient& cb);
    int sub_id_ = -1;
};

class Service {
public:
    static std::unique_ptr<Service> create(int domainId, std::string serviceName, IService& cb);
    ~Service();
    // Inline no-op IClient report forwarders (stub).
    void EventLogMessages(LogMessageListType const& /*unused*/) {}
    void ReportLogSettings(LogSettingsType const& /*unused*/, bool const& /*unused*/) {}
    void ResponseLogMessages(LogMessageRequestType const& /*unused*/, LogMessageListType const& /*unused*/) {}
    // Inline no-op IService command forwarders (stub).
    void CmdSetLogSettings(LogSettingsType const& /*unused*/) {}
    void RequestLogMessages(LogMessageRequestType const& /*unused*/) {}



private:
    Service(int domain, std::string svc, IService& cb);
    int sub_id_ = -1;
};

}  // namespace M_Logging
