// SPDX-License-Identifier: MIT
// Stub SDK header for M_Manipulator.
#pragma once
#include "M_Manipulator_stub.hpp"   // generated by pipegen (struct types + IClient/IService shells)
#include <memory>
#include <string>

namespace M_Manipulator {

class Client {
public:
    static std::unique_ptr<Client> create(int domainId, std::string serviceName, IClient& cb);
    ~Client();
    // Inline no-op IClient report forwarders (stub).
    void ReportManipulatorSettings(ManipulatorSettingsType const& /*unused*/) {}
    void ReportManipulatorStatus(ManipulatorStatusType const& /*unused*/, bool const& /*unused*/) {}
    void ReportLinkStatus(::std::string const& /*unused*/, LinkStatusType const& /*unused*/) {}


private:
    Client(int domain, std::string svc, IClient& cb);
    int sub_id_ = -1;
};

class Service {
public:
    static std::unique_ptr<Service> create(int domainId, std::string serviceName, IService& cb);
    ~Service();
    // Inline no-op IClient report forwarders (stub).
    void ReportManipulatorSettings(ManipulatorSettingsType const& /*unused*/) {}
    void ReportManipulatorStatus(ManipulatorStatusType const& /*unused*/, bool const& /*unused*/) {}
    void ReportLinkStatus(::std::string const& /*unused*/, LinkStatusType const& /*unused*/) {}


private:
    Service(int domain, std::string svc, IService& cb);
    int sub_id_ = -1;
};

}  // namespace M_Manipulator
