// SPDX-License-Identifier: MIT
// Stub SDK header for M_MetSensor.
#pragma once
#include "M_MetSensor_stub.hpp"   // generated by pipegen (struct types + IClient/IService shells)
#include <memory>
#include <string>

namespace M_MetSensor {

class Client {
public:
    static std::unique_ptr<Client> create(int domainId, std::string serviceName, IClient& cb);
    ~Client();
    // Inline no-op IService command forwarders (stub).
    void CmdIsMetSensorAlive() {}
    // Inline no-op IClient report forwarders (stub).
    void ReportMetSensorSettings(MetSensorSettingsType const& /*unused*/) {}
    void ReportMetSensorStatus(AtmosphericType const& /*unused*/, bool const& /*unused*/) {}



private:
    Client(int domain, std::string svc, IClient& cb);
    int sub_id_ = -1;
};

class Service {
public:
    static std::unique_ptr<Service> create(int domainId, std::string serviceName, IService& cb);
    ~Service();
    // Inline no-op IClient report forwarders (stub).
    void ReportMetSensorSettings(MetSensorSettingsType const& /*unused*/) {}
    void ReportMetSensorStatus(AtmosphericType const& /*unused*/, bool const& /*unused*/) {}
    // Inline no-op IService command forwarders (stub).
    void CmdIsMetSensorAlive() {}



private:
    Service(int domain, std::string svc, IService& cb);
    int sub_id_ = -1;
};

}  // namespace M_MetSensor
