// SPDX-License-Identifier: MIT
// Stub SDK header for M_MissionCtrl.
#pragma once
#include "M_MissionCtrl_stub.hpp"   // generated by pipegen (struct types + IClient/IService shells)
#include <memory>
#include <string>

namespace M_MissionCtrl {

class Client {
public:
    static std::unique_ptr<Client> create(int domainId, std::string serviceName, IClient& cb);
    ~Client();

    // No-op IService command forwarders (stub implementation).
    void CmdPerformAction(::M_MissionCtrl::CommandedActionType const& /*unused*/) {}
    void CmdAbortMission(::std::string const& /*unused*/) {}
    void CmdDeleteMission(::std::string const& /*unused*/) {}
    // Inline no-op IService command forwarders (stub).
    void CmdPerformMission(::std::string const& /*unused*/, MissionOptionalType const& /*unused*/) {}
    void ConfigStoreMission(::std::string const& /*unused*/, MissionType const& /*unused*/, bool const& /*unused*/) {}
    // Inline no-op IClient report forwarders (stub).
    void ReportMissionCtrlSettings(MissionCtrlSettingsType const& /*unused*/) {}
    void ReportMissionStatus(MissionStatusType const& /*unused*/, bool const& /*unused*/) {}
    void ReportStoredMission(::std::string const& /*unused*/, MissionType const& /*unused*/, bool const& /*unused*/) {}
    void ReportMap(MultiLevelSurfaceMapType const& /*unused*/) {}



private:
    Client(int domain, std::string svc, IClient& cb);
    int sub_id_ = -1;
};

class Service {
public:
    static std::unique_ptr<Service> create(int domainId, std::string serviceName, IService& cb);
    ~Service();
    // Inline no-op IClient report forwarders (stub).
    void ReportMissionCtrlSettings(MissionCtrlSettingsType const& /*unused*/) {}
    void ReportMissionStatus(MissionStatusType const& /*unused*/, bool const& /*unused*/) {}
    void ReportStoredMission(::std::string const& /*unused*/, MissionType const& /*unused*/, bool const& /*unused*/) {}
    void ReportMap(MultiLevelSurfaceMapType const& /*unused*/) {}
    // Inline no-op IService command forwarders (stub).
    void CmdPerformAction(CommandedActionType const& /*unused*/) {}
    void CmdPerformMission(::std::string const& /*unused*/, MissionOptionalType const& /*unused*/) {}
    void CmdAbortMission(::std::string const& /*unused*/) {}
    void ConfigStoreMission(::std::string const& /*unused*/, MissionType const& /*unused*/, bool const& /*unused*/) {}
    void CmdDeleteMission(::std::string const& /*unused*/) {}



private:
    Service(int domain, std::string svc, IService& cb);
    int sub_id_ = -1;
};

}  // namespace M_MissionCtrl
