// SPDX-License-Identifier: MIT
#pragma once
#include "M_Mount_stub.hpp"   // generated by pipegen (struct types + IClient/IService shells)
#include <memory>
#include <string>

namespace M_Mount {

class Client {
public:
    static std::unique_ptr<Client> create(int domainId, std::string serviceName, IClient&);
    ~Client();

    // Stub IService command forwarders for single-param ops.
    void ConfigTgtAssignmentSearchPattern(TgtAssignmentSearchPatternType const& /*SearchPatternParams*/) {}
    void ConfigSlewLimits(AngularLimitType const& /*SlewLimits*/) {}
    void CmdMoveToStoredPosition(std::string const& /*Id*/) {}
    void CmdAutoDriftCompensation(bool /*IsEnabled*/) {}
    void CmdAllowExternalDriftCompensation(bool /*IsAllowed*/) {}
    void CmdHorizontalAiming(bool /*IsEnabled*/) {}
    void CmdSetOperationalModeRateAid(bool /*Activate*/) {}
    // Inline no-op IService command forwarders (stub).
    void ConfigMaximumRate(::M_Common::AngleRateDegreesPerSecOptionalType const& /*unused*/, ::M_Common::AngleRateDegreesPerSecOptionalType const& /*unused*/) {}
    void ConfigInputSource(bool const& /*unused*/, ::M_Common::StringListType const& /*unused*/) {}
    void ConfigTgtAssignmentInputSource(bool const& /*unused*/, ::M_Common::StringListType const& /*unused*/) {}
    void ConfigTgtAssignmentSearchInputSource(bool const& /*unused*/, ::M_Common::StringListType const& /*unused*/) {}
    void ConfigLeadingDevice(::M_Common::LongOptionalType const& /*unused*/) {}
    void ConfigSlavedDevice(::M_Common::LongOptionalType const& /*unused*/) {}
    void ConfigStorePosition(::std::string const& /*unused*/, ::M_Common::AngleDegreesType const& /*unused*/, ::M_Common::AngleDegreesType const& /*unused*/, bool const& /*unused*/) {}
    void CmdMode(ModeCommand::Type const& /*unused*/) {}
    void CmdTgtAssignmentSearchAction(TgtAssignmentSearchCmdKind::Type const& /*unused*/) {}
    void CmdManualDriftCompensation(::M_Common::AngleRateDegreesPerSecType const& /*unused*/, ::M_Common::AngleRateDegreesPerSecType const& /*unused*/, bool const& /*unused*/) {}
    void NotifyAngle(::std::string const& /*unused*/, ::M_Common::AngleDegreesType const& /*unused*/, ::M_Common::AngleDegreesType const& /*unused*/, MountAngleParamsType const& /*unused*/) {}
    void NotifyTgtAssignment(::std::string const& /*unused*/, ::M_Common::PositionType const& /*unused*/, ::M_Common::LinearVelocityOptionalType const& /*unused*/, ::M_Common::TimeType const& /*unused*/, MountAngleParamsType const& /*unused*/) {}
    void NotifyRateRelative(::std::string const& /*unused*/, ::M_Common::AngleRateDegreesPerSecType const& /*unused*/, ::M_Common::AngleRateDegreesPerSecType const& /*unused*/) {}
    void NotifyRateAbsolute(::std::string const& /*unused*/, ::M_Common::AngleRateDegreesPerSecType const& /*unused*/, ::M_Common::AngleRateDegreesPerSecType const& /*unused*/) {}
    void NotifyRateScaled(::std::string const& /*unused*/, ScaledRateOptionalType const& /*unused*/) {}
    // Inline no-op IClient report forwarders (stub).
    void ReportMountSettings(MountSettingsType const& /*unused*/) {}
    void ReportMountStatus(MountStatusType const& /*unused*/, bool const& /*unused*/) {}
    void ReportMountPosition(MountPositionType const& /*unused*/) {}
    void ReportTgtAssignmentSearchOffset(::M_Common::SphericalPositionType const& /*unused*/) {}
    void ReportTgtAssignmentPosition(::M_Common::PositionType const& /*unused*/) {}
    void ReportTgtAssignmentVelocity(::M_Common::LinearVelocityOptionalType const& /*unused*/) {}



private:
    Client(int domain, std::string svc, IClient& cb);
    int sub_id_;
};

class Service {
public:
    static std::unique_ptr<Service> create(int domainId, std::string serviceName, IService& cb);
    ~Service();
    // Inline no-op IClient report forwarders (stub).
    void ReportMountSettings(MountSettingsType const& /*unused*/) {}
    void ReportMountStatus(MountStatusType const& /*unused*/, bool const& /*unused*/) {}
    void ReportMountPosition(MountPositionType const& /*unused*/) {}
    void ReportTgtAssignmentSearchOffset(::M_Common::SphericalPositionType const& /*unused*/) {}
    void ReportTgtAssignmentPosition(::M_Common::PositionType const& /*unused*/) {}
    void ReportTgtAssignmentVelocity(::M_Common::LinearVelocityOptionalType const& /*unused*/) {}
    // Inline no-op IService command forwarders (stub).
    void ConfigMaximumRate(::M_Common::AngleRateDegreesPerSecOptionalType const& /*unused*/, ::M_Common::AngleRateDegreesPerSecOptionalType const& /*unused*/) {}
    void ConfigInputSource(bool const& /*unused*/, ::M_Common::StringListType const& /*unused*/) {}
    void ConfigTgtAssignmentInputSource(bool const& /*unused*/, ::M_Common::StringListType const& /*unused*/) {}
    void ConfigTgtAssignmentSearchInputSource(bool const& /*unused*/, ::M_Common::StringListType const& /*unused*/) {}
    void ConfigTgtAssignmentSearchPattern(TgtAssignmentSearchPatternType const& /*unused*/) {}
    void ConfigLeadingDevice(::M_Common::LongOptionalType const& /*unused*/) {}
    void ConfigSlavedDevice(::M_Common::LongOptionalType const& /*unused*/) {}
    void ConfigSlewLimits(AngularLimitType const& /*unused*/) {}
    void ConfigStorePosition(::std::string const& /*unused*/, ::M_Common::AngleDegreesType const& /*unused*/, ::M_Common::AngleDegreesType const& /*unused*/, bool const& /*unused*/) {}
    void CmdMoveToStoredPosition(::std::string const& /*unused*/) {}
    void CmdMode(ModeCommand::Type const& /*unused*/) {}
    void CmdTgtAssignmentSearchAction(TgtAssignmentSearchCmdKind::Type const& /*unused*/) {}
    void CmdAutoDriftCompensation(bool const& /*unused*/) {}
    void CmdManualDriftCompensation(::M_Common::AngleRateDegreesPerSecType const& /*unused*/, ::M_Common::AngleRateDegreesPerSecType const& /*unused*/, bool const& /*unused*/) {}
    void CmdAllowExternalDriftCompensation(bool const& /*unused*/) {}
    void CmdHorizontalAiming(bool const& /*unused*/) {}
    void CmdSetOperationalModeRateAid(bool const& /*unused*/) {}
    void NotifyAngle(::std::string const& /*unused*/, ::M_Common::AngleDegreesType const& /*unused*/, ::M_Common::AngleDegreesType const& /*unused*/, MountAngleParamsType const& /*unused*/) {}
    void NotifyTgtAssignment(::std::string const& /*unused*/, ::M_Common::PositionType const& /*unused*/, ::M_Common::LinearVelocityOptionalType const& /*unused*/, ::M_Common::TimeType const& /*unused*/, MountAngleParamsType const& /*unused*/) {}
    void NotifyRateRelative(::std::string const& /*unused*/, ::M_Common::AngleRateDegreesPerSecType const& /*unused*/, ::M_Common::AngleRateDegreesPerSecType const& /*unused*/) {}
    void NotifyRateAbsolute(::std::string const& /*unused*/, ::M_Common::AngleRateDegreesPerSecType const& /*unused*/, ::M_Common::AngleRateDegreesPerSecType const& /*unused*/) {}
    void NotifyRateScaled(::std::string const& /*unused*/, ScaledRateOptionalType const& /*unused*/) {}


private:
    Service(int domain, std::string svc, IService& cb);
    int sub_id_ = -1;
};

// Test/simulator hook — directly publish a position as if a Mount service had done it.
void stub_publish_position(int domainId, std::string const& serviceName,
                           MountPositionType const& pos);

}  // namespace M_Mount
