// SPDX-License-Identifier: MIT
// Stub SDK header for M_MultiMount.
#pragma once
#include "M_MultiMount_stub.hpp"   // generated by pipegen (struct types + IClient/IService shells)
#include <memory>
#include <string>

namespace M_MultiMount {

class Client {
public:
    static std::unique_ptr<Client> create(int domainId, std::string serviceName, IClient& cb);
    ~Client();

    // No-op IService command forwarders (stub implementation).
    void CmdMode(::M_Common::OperationModeType const& /*unused*/) {}
    void CmdAutoDriftCompensation(bool const& /*unused*/) {}
    void CmdAllowExternalDriftCompensation(bool const& /*unused*/) {}
    // Inline no-op IService command forwarders (stub).
    void ConfigInputSource(bool const& /*unused*/, ::M_Common::StringListType const& /*unused*/) {}
    void ConfigAssignmentInputSource(bool const& /*unused*/, ::M_Common::StringListType const& /*unused*/) {}
    void ConfigSlavedDevice(::M_Common::LongOptionalType const& /*unused*/) {}
    void ConfigLeadingDevice(::M_Common::LongOptionalType const& /*unused*/) {}
    void CmdManualDriftCompensation(::M_KinematicChain::AxisRotationListType const& /*unused*/, bool const& /*unused*/) {}
    void NotifyAssignment(::std::string const& /*unused*/, ::M_Common::PositionType const& /*unused*/, ::M_Common::LinearVelocityOptionalType const& /*unused*/, ::M_KinematicChain::AxisRotationType const& /*unused*/) {}
    // Inline no-op IClient report forwarders (stub).
    void ReportMountSettings(MountSettingsType const& /*unused*/) {}
    void ReportMountStatus(MountStatusType const& /*unused*/, bool const& /*unused*/) {}
    void ReportAssignmentPosition(::M_Common::PositionType const& /*unused*/) {}
    void ReportAssignmentVelocity(::M_Common::LinearVelocityOptionalType const& /*unused*/) {}



private:
    Client(int domain, std::string svc, IClient& cb);
    int sub_id_ = -1;
};

class Service {
public:
    static std::unique_ptr<Service> create(int domainId, std::string serviceName, IService& cb);
    ~Service();
    // Inline no-op IClient report forwarders (stub).
    void ReportMountSettings(MountSettingsType const& /*unused*/) {}
    void ReportMountStatus(MountStatusType const& /*unused*/, bool const& /*unused*/) {}
    void ReportAssignmentPosition(::M_Common::PositionType const& /*unused*/) {}
    void ReportAssignmentVelocity(::M_Common::LinearVelocityOptionalType const& /*unused*/) {}
    // Inline no-op IService command forwarders (stub).
    void ConfigInputSource(bool const& /*unused*/, ::M_Common::StringListType const& /*unused*/) {}
    void ConfigAssignmentInputSource(bool const& /*unused*/, ::M_Common::StringListType const& /*unused*/) {}
    void ConfigSlavedDevice(::M_Common::LongOptionalType const& /*unused*/) {}
    void ConfigLeadingDevice(::M_Common::LongOptionalType const& /*unused*/) {}
    void CmdMode(::M_Common::OperationModeType const& /*unused*/) {}
    void CmdAutoDriftCompensation(bool const& /*unused*/) {}
    void CmdManualDriftCompensation(::M_KinematicChain::AxisRotationListType const& /*unused*/, bool const& /*unused*/) {}
    void CmdAllowExternalDriftCompensation(bool const& /*unused*/) {}
    void NotifyAssignment(::std::string const& /*unused*/, ::M_Common::PositionType const& /*unused*/, ::M_Common::LinearVelocityOptionalType const& /*unused*/, ::M_KinematicChain::AxisRotationType const& /*unused*/) {}



private:
    Service(int domain, std::string svc, IService& cb);
    int sub_id_ = -1;
};

}  // namespace M_MultiMount
