// SPDX-License-Identifier: MIT
// Stub SDK header for M_ObjectManager.
#pragma once
#include "M_ObjectManager_stub.hpp"   // generated by pipegen (struct types + IClient/IService shells)
#include <memory>
#include <string>

namespace M_ObjectManager {

class Client {
public:
    static std::unique_ptr<Client> create(int domainId, std::string serviceName, IClient& cb);
    ~Client();
    // Inline no-op IService command forwarders (stub).
    void RequestPosition(::M_Common::ObjectIdType const& /*unused*/, ::M_Common::PositionType const& /*unused*/, ::std::string const& /*unused*/) {}
    void CmdAddUpdatePoint(::M_Common::ObjectIdType const& /*unused*/, PointObjectType const& /*unused*/) {}
    void CmdModifyPoint(::M_Common::ObjectIdType const& /*unused*/, ModifyPointType const& /*unused*/) {}
    void CmdAddUpdateMultiPoint(::M_Common::ObjectIdType const& /*unused*/, MultiPointObjectType const& /*unused*/) {}
    void CmdModifyMultiPoint(::M_Common::ObjectIdType const& /*unused*/, ModifyMultiPointType const& /*unused*/) {}
    void CmdRemove(::M_Common::ObjectIdType const& /*unused*/) {}
    // Inline no-op IClient report forwarders (stub).
    void ReportObjectManagerSettings(ObjectManagerSettingsType const& /*unused*/) {}
    void ResponsePosition(::M_Common::ObjectIdType const& /*unused*/, ::M_Common::PositionType const& /*unused*/) {}
    void ReportOwnInfo(::std::string const& /*unused*/, OwnInfoType const& /*unused*/, bool const& /*unused*/) {}
    void ReportPoint(::M_Common::ObjectIdType const& /*unused*/, PointObjectType const& /*unused*/, bool const& /*unused*/) {}
    void ReportMultiPoint(::M_Common::ObjectIdType const& /*unused*/, MultiPointObjectType const& /*unused*/, bool const& /*unused*/) {}
    void ReportCoordinateTransformations(::M_Common::CoordinateTransformationListType const& /*unused*/, bool const& /*unused*/) {}
    void EventObjectChanged(::M_Common::ObjectIdType const& /*unused*/, ParameterDifferenceType const& /*unused*/) {}



private:
    Client(int domain, std::string svc, IClient& cb);
    int sub_id_ = -1;
};

class Service {
public:
    static std::unique_ptr<Service> create(int domainId, std::string serviceName, IService& cb);
    ~Service();
    // Inline no-op IClient report forwarders (stub).
    void ReportObjectManagerSettings(ObjectManagerSettingsType const& /*unused*/) {}
    void ResponsePosition(::M_Common::ObjectIdType const& /*unused*/, ::M_Common::PositionType const& /*unused*/) {}
    void ReportOwnInfo(::std::string const& /*unused*/, OwnInfoType const& /*unused*/, bool const& /*unused*/) {}
    void ReportPoint(::M_Common::ObjectIdType const& /*unused*/, PointObjectType const& /*unused*/, bool const& /*unused*/) {}
    void ReportMultiPoint(::M_Common::ObjectIdType const& /*unused*/, MultiPointObjectType const& /*unused*/, bool const& /*unused*/) {}
    void ReportCoordinateTransformations(::M_Common::CoordinateTransformationListType const& /*unused*/, bool const& /*unused*/) {}
    void EventObjectChanged(::M_Common::ObjectIdType const& /*unused*/, ParameterDifferenceType const& /*unused*/) {}
    // Inline no-op IService command forwarders (stub).
    void RequestPosition(::M_Common::ObjectIdType const& /*unused*/, ::M_Common::PositionType const& /*unused*/, ::std::string const& /*unused*/) {}
    void CmdAddUpdatePoint(::M_Common::ObjectIdType const& /*unused*/, PointObjectType const& /*unused*/) {}
    void CmdModifyPoint(::M_Common::ObjectIdType const& /*unused*/, ModifyPointType const& /*unused*/) {}
    void CmdAddUpdateMultiPoint(::M_Common::ObjectIdType const& /*unused*/, MultiPointObjectType const& /*unused*/) {}
    void CmdModifyMultiPoint(::M_Common::ObjectIdType const& /*unused*/, ModifyMultiPointType const& /*unused*/) {}
    void CmdRemove(::M_Common::ObjectIdType const& /*unused*/) {}



private:
    Service(int domain, std::string svc, IService& cb);
    int sub_id_ = -1;
};

}  // namespace M_ObjectManager
