// SPDX-License-Identifier: MIT
// Stub SDK header for M_OverlayCtrl.
#pragma once
#include "M_OverlayCtrl_stub.hpp"   // generated by pipegen (struct types + IClient/IService shells)
#include <memory>
#include <string>

namespace M_OverlayCtrl {

class Client {
public:
    static std::unique_ptr<Client> create(int domainId, std::string serviceName, IClient& cb);
    ~Client();
    // Inline no-op IService command forwarders (stub).
    void ConfigEnableOverlay(::std::string const& /*unused*/, bool const& /*unused*/, bool const& /*unused*/) {}
    void ConfigColourStyle(::std::string const& /*unused*/, ::M_Common::ColourStyleType const& /*unused*/, bool const& /*unused*/) {}
    // Inline no-op IClient report forwarders (stub).
    void ReportOverlayCtrlSettings(OverlayCtrlSettingsType const& /*unused*/) {}
    void ReportOverlayStatus(::std::string const& /*unused*/, OverlayCtrlStatusType const& /*unused*/, bool const& /*unused*/) {}



private:
    Client(int domain, std::string svc, IClient& cb);
    int sub_id_ = -1;
};

class Service {
public:
    static std::unique_ptr<Service> create(int domainId, std::string serviceName, IService& cb);
    ~Service();
    // Inline no-op IClient report forwarders (stub).
    void ReportOverlayCtrlSettings(OverlayCtrlSettingsType const& /*unused*/) {}
    void ReportOverlayStatus(::std::string const& /*unused*/, OverlayCtrlStatusType const& /*unused*/, bool const& /*unused*/) {}
    // Inline no-op IService command forwarders (stub).
    void ConfigEnableOverlay(::std::string const& /*unused*/, bool const& /*unused*/, bool const& /*unused*/) {}
    void ConfigColourStyle(::std::string const& /*unused*/, ::M_Common::ColourStyleType const& /*unused*/, bool const& /*unused*/) {}



private:
    Service(int domain, std::string svc, IService& cb);
    int sub_id_ = -1;
};

}  // namespace M_OverlayCtrl
