// SPDX-License-Identifier: MIT
// Stub SDK header for M_RecordingCtrl.
#pragma once
#include "M_RecordingCtrl_stub.hpp"   // generated by pipegen (struct types + IClient/IService shells)
#include <memory>
#include <string>

namespace M_RecordingCtrl {

class Client {
public:
    static std::unique_ptr<Client> create(int domainId, std::string serviceName, IClient& cb);
    ~Client();
    // Inline no-op IService command forwarders (stub).
    void CmdStartRecording(VideoChannelListType const& /*unused*/) {}
    void CmdCaptureVideoCutout(::M_Common::StringListType const& /*unused*/, ::M_Common::TimeType const& /*unused*/, ::M_Common::TimeType const& /*unused*/, ::std::string const& /*unused*/) {}
    void CmdStopRecording(::M_Common::StringListType const& /*unused*/) {}
    void CmdRemoveVideoCutout(::std::string const& /*unused*/, ::M_Common::TimeType const& /*unused*/, ::M_Common::TimeType const& /*unused*/) {}
    void CmdRemoveAllVideoCutouts() {}
    void CmdCaptureImage(::M_Common::StringListType const& /*unused*/) {}
    // Inline no-op IClient report forwarders (stub).
    void ReportRecordingSettings(RecordingSettingsType const& /*unused*/) {}
    void ReportRecordingStatus(RecordingStatusType const& /*unused*/, bool const& /*unused*/) {}



private:
    Client(int domain, std::string svc, IClient& cb);
    int sub_id_ = -1;
};

class Service {
public:
    static std::unique_ptr<Service> create(int domainId, std::string serviceName, IService& cb);
    ~Service();
    // Inline no-op IClient report forwarders (stub).
    void ReportRecordingSettings(RecordingSettingsType const& /*unused*/) {}
    void ReportRecordingStatus(RecordingStatusType const& /*unused*/, bool const& /*unused*/) {}
    // Inline no-op IService command forwarders (stub).
    void CmdStartRecording(VideoChannelListType const& /*unused*/) {}
    void CmdCaptureVideoCutout(::M_Common::StringListType const& /*unused*/, ::M_Common::TimeType const& /*unused*/, ::M_Common::TimeType const& /*unused*/, ::std::string const& /*unused*/) {}
    void CmdStopRecording(::M_Common::StringListType const& /*unused*/) {}
    void CmdRemoveVideoCutout(::std::string const& /*unused*/, ::M_Common::TimeType const& /*unused*/, ::M_Common::TimeType const& /*unused*/) {}
    void CmdRemoveAllVideoCutouts() {}
    void CmdCaptureImage(::M_Common::StringListType const& /*unused*/) {}



private:
    Service(int domain, std::string svc, IService& cb);
    int sub_id_ = -1;
};

}  // namespace M_RecordingCtrl
