// SPDX-License-Identifier: MIT
// Stub SDK header for M_ReplayCtrl.
#pragma once
#include "M_ReplayCtrl_stub.hpp"   // generated by pipegen (struct types + IClient/IService shells)
#include <memory>
#include <string>

namespace M_ReplayCtrl {

class Client {
public:
    static std::unique_ptr<Client> create(int domainId, std::string serviceName, IClient& cb);
    ~Client();
    // Inline no-op IService command forwarders (stub).
    void CmdStartReplay(ReplayChannelInfoListType const& /*unused*/, ::M_Common::TimeType const& /*unused*/, ::M_Common::TimeOptionalType const& /*unused*/, ReplayLoopMode::Type const& /*unused*/, ReplayStartMode::Type const& /*unused*/) {}
    void CmdLoopReplay(::M_Common::StringListType const& /*unused*/) {}
    void CmdStopReplay(::M_Common::StringListType const& /*unused*/) {}
    void CmdPauseReplay(::M_Common::StringListType const& /*unused*/) {}
    void CmdResumeReplay(::M_Common::StringListType const& /*unused*/) {}
    void CmdStepReplay(::M_Common::StringListType const& /*unused*/) {}
    // Inline no-op IClient report forwarders (stub).
    void ReportReplaySettings(ReplaySettingsType const& /*unused*/) {}
    void ReportReplayStatus(ReplayStatusType const& /*unused*/, bool const& /*unused*/) {}



private:
    Client(int domain, std::string svc, IClient& cb);
    int sub_id_ = -1;
};

class Service {
public:
    static std::unique_ptr<Service> create(int domainId, std::string serviceName, IService& cb);
    ~Service();
    // Inline no-op IClient report forwarders (stub).
    void ReportReplaySettings(ReplaySettingsType const& /*unused*/) {}
    void ReportReplayStatus(ReplayStatusType const& /*unused*/, bool const& /*unused*/) {}
    // Inline no-op IService command forwarders (stub).
    void CmdStartReplay(ReplayChannelInfoListType const& /*unused*/, ::M_Common::TimeType const& /*unused*/, ::M_Common::TimeOptionalType const& /*unused*/, ReplayLoopMode::Type const& /*unused*/, ReplayStartMode::Type const& /*unused*/) {}
    void CmdLoopReplay(::M_Common::StringListType const& /*unused*/) {}
    void CmdStopReplay(::M_Common::StringListType const& /*unused*/) {}
    void CmdPauseReplay(::M_Common::StringListType const& /*unused*/) {}
    void CmdResumeReplay(::M_Common::StringListType const& /*unused*/) {}
    void CmdStepReplay(::M_Common::StringListType const& /*unused*/) {}



private:
    Service(int domain, std::string svc, IService& cb);
    int sub_id_ = -1;
};

}  // namespace M_ReplayCtrl
