// SPDX-License-Identifier: MIT
// Stub SDK header for M_ScanCtrl.
#pragma once
#include "M_ScanCtrl_stub.hpp"   // generated by pipegen (struct types + IClient/IService shells)
#include <memory>
#include <string>

namespace M_ScanCtrl {

class Client {
public:
    static std::unique_ptr<Client> create(int domainId, std::string serviceName, IClient& cb);
    ~Client();

    // No-op IService command forwarders (stub implementation).
    void CmdDeleteScanPattern(::std::string const& /*unused*/) {}
    // Inline no-op IService command forwarders (stub).
    void CmdScanPattern(::std::string const& /*unused*/, ScanPatternOptionalType const& /*unused*/) {}
    void CmdScanAction(ScanCtrlMode::Type const& /*unused*/) {}
    void ConfigStoreScanPattern(::std::string const& /*unused*/, ScanPatternType const& /*unused*/, bool const& /*unused*/) {}
    // Inline no-op IClient report forwarders (stub).
    void ReportScanCtrlSettings(ScanCtrlSettingsType const& /*unused*/) {}
    void ReportScanCtrlStatus(ScanCtrlStatusType const& /*unused*/, bool const& /*unused*/) {}
    void ReportStoredScanPattern(::std::string const& /*unused*/, ScanPatternType const& /*unused*/, bool const& /*unused*/) {}
    void ReportAssignmentSearchOffset(::M_Common::PositionType const& /*unused*/) {}



private:
    Client(int domain, std::string svc, IClient& cb);
    int sub_id_ = -1;
};

class Service {
public:
    static std::unique_ptr<Service> create(int domainId, std::string serviceName, IService& cb);
    ~Service();
    // Inline no-op IClient report forwarders (stub).
    void ReportScanCtrlSettings(ScanCtrlSettingsType const& /*unused*/) {}
    void ReportScanCtrlStatus(ScanCtrlStatusType const& /*unused*/, bool const& /*unused*/) {}
    void ReportStoredScanPattern(::std::string const& /*unused*/, ScanPatternType const& /*unused*/, bool const& /*unused*/) {}
    void ReportAssignmentSearchOffset(::M_Common::PositionType const& /*unused*/) {}
    // Inline no-op IService command forwarders (stub).
    void CmdScanPattern(::std::string const& /*unused*/, ScanPatternOptionalType const& /*unused*/) {}
    void CmdScanAction(ScanCtrlMode::Type const& /*unused*/) {}
    void ConfigStoreScanPattern(::std::string const& /*unused*/, ScanPatternType const& /*unused*/, bool const& /*unused*/) {}
    void CmdDeleteScanPattern(::std::string const& /*unused*/) {}



private:
    Service(int domain, std::string svc, IService& cb);
    int sub_id_ = -1;
};

}  // namespace M_ScanCtrl
