// SPDX-License-Identifier: MIT
// Stub SDK header for M_SectorSelection.
#pragma once
#include "M_SectorSelection_stub.hpp"   // generated by pipegen (struct types + IClient/IService shells)
#include <memory>
#include <string>

namespace M_SectorSelection {

class Client {
public:
    static std::unique_ptr<Client> create(int domainId, std::string serviceName, IClient& cb);
    ~Client();
    // Inline no-op IService command forwarders (stub).
    void CmdSelectSector(::M_Common::ULongListType const& /*unused*/) {}
    // Inline no-op IClient report forwarders (stub).
    void ReportSectorSelectionSettings(SectorSelectionSettingsType const& /*unused*/) {}
    void ReportSectorDefinitions(SectorDefinitionListType const& /*unused*/) {}
    void ReportSectorSelectionStatus(SectorSelectionStatusType const& /*unused*/, bool const& /*unused*/) {}



private:
    Client(int domain, std::string svc, IClient& cb);
    int sub_id_ = -1;
};

class Service {
public:
    static std::unique_ptr<Service> create(int domainId, std::string serviceName, IService& cb);
    ~Service();
    // Inline no-op IClient report forwarders (stub).
    void ReportSectorSelectionSettings(SectorSelectionSettingsType const& /*unused*/) {}
    void ReportSectorDefinitions(SectorDefinitionListType const& /*unused*/) {}
    void ReportSectorSelectionStatus(SectorSelectionStatusType const& /*unused*/, bool const& /*unused*/) {}
    // Inline no-op IService command forwarders (stub).
    void CmdSelectSector(::M_Common::ULongListType const& /*unused*/) {}



private:
    Service(int domain, std::string svc, IService& cb);
    int sub_id_ = -1;
};

}  // namespace M_SectorSelection
