// SPDX-License-Identifier: MIT
// Stub SDK header for M_Sensor.
#pragma once
#include "M_Sensor_stub.hpp"   // generated by pipegen (struct types + IClient/IService shells)
#include <memory>
#include <string>

namespace M_Sensor {

class Client {
public:
    static std::unique_ptr<Client> create(int domainId, std::string serviceName, IClient& cb);
    ~Client();

    // No-op IService command forwarders (stub implementation).
    void CmdDeactivateSensor(bool const& /*unused*/) {}
    // Inline no-op IService command forwarders (stub).
    void CmdIsSensorAlive() {}
    void CmdDeleteTracks(::M_Common::ObjectIdListType const& /*unused*/) {}
    void CmdDeleteAllTracks() {}
    // Inline no-op IClient report forwarders (stub).
    void ReportSensorSettings(SensorSettingsType const& /*unused*/) {}
    void ReportSensorStatus(SensorStatusType const& /*unused*/, bool const& /*unused*/) {}
    void EventSensorDetection(::M_Common::ObjectIdType const& /*unused*/, SensorDetectionType const& /*unused*/) {}
    void ReportSensorTrack(::M_Common::ObjectIdType const& /*unused*/, SensorDetectionType const& /*unused*/, bool const& /*unused*/) {}



private:
    Client(int domain, std::string svc, IClient& cb);
    int sub_id_ = -1;
};

class Service {
public:
    static std::unique_ptr<Service> create(int domainId, std::string serviceName, IService& cb);
    ~Service();
    // Inline no-op IClient report forwarders (stub).
    void ReportSensorSettings(SensorSettingsType const& /*unused*/) {}
    void ReportSensorStatus(SensorStatusType const& /*unused*/, bool const& /*unused*/) {}
    void EventSensorDetection(::M_Common::ObjectIdType const& /*unused*/, SensorDetectionType const& /*unused*/) {}
    void ReportSensorTrack(::M_Common::ObjectIdType const& /*unused*/, SensorDetectionType const& /*unused*/, bool const& /*unused*/) {}
    // Inline no-op IService command forwarders (stub).
    void CmdIsSensorAlive() {}
    void CmdDeleteTracks(::M_Common::ObjectIdListType const& /*unused*/) {}
    void CmdDeleteAllTracks() {}
    void CmdDeactivateSensor(bool const& /*unused*/) {}



private:
    Service(int domain, std::string svc, IService& cb);
    int sub_id_ = -1;
};

}  // namespace M_Sensor
