// SPDX-License-Identifier: MIT
// Stub SDK header for M_SignalProcessing.
#pragma once
#include "M_SignalProcessing_stub.hpp"   // generated by pipegen (struct types + IClient/IService shells)
#include <memory>
#include <string>

namespace M_SignalProcessing {

class Client {
public:
    static std::unique_ptr<Client> create(int domainId, std::string serviceName, IClient& cb);
    ~Client();
    // Inline no-op IService command forwarders (stub).
    void ConfigHfComponent(::std::string const& /*unused*/, HfComponentType const& /*unused*/, bool const& /*unused*/) {}
    void ConfigSoi(::std::string const& /*unused*/, SoiType const& /*unused*/, bool const& /*unused*/) {}
    void ConfigBandScanSubscription(::std::string const& /*unused*/, BandScanType const& /*unused*/, bool const& /*unused*/) {}
    // Inline no-op IClient report forwarders (stub).
    void ReportSignalProcessingSettings(SignalProcessingSettingsType const& /*unused*/) {}
    void ReportHfComponent(::std::string const& /*unused*/, HfComponentType const& /*unused*/, bool const& /*unused*/) {}
    void ReportSoi(::std::string const& /*unused*/, SoiType const& /*unused*/, bool const& /*unused*/) {}



private:
    Client(int domain, std::string svc, IClient& cb);
    int sub_id_ = -1;
};

class Service {
public:
    static std::unique_ptr<Service> create(int domainId, std::string serviceName, IService& cb);
    ~Service();
    // Inline no-op IClient report forwarders (stub).
    void ReportSignalProcessingSettings(SignalProcessingSettingsType const& /*unused*/) {}
    void ReportHfComponent(::std::string const& /*unused*/, HfComponentType const& /*unused*/, bool const& /*unused*/) {}
    void ReportSoi(::std::string const& /*unused*/, SoiType const& /*unused*/, bool const& /*unused*/) {}
    // Inline no-op IService command forwarders (stub).
    void ConfigHfComponent(::std::string const& /*unused*/, HfComponentType const& /*unused*/, bool const& /*unused*/) {}
    void ConfigSoi(::std::string const& /*unused*/, SoiType const& /*unused*/, bool const& /*unused*/) {}
    void ConfigBandScanSubscription(::std::string const& /*unused*/, BandScanType const& /*unused*/, bool const& /*unused*/) {}



private:
    Service(int domain, std::string svc, IService& cb);
    int sub_id_ = -1;
};

}  // namespace M_SignalProcessing
