// SPDX-License-Identifier: MIT
// Stub SDK header for M_SignalGenerator.
#pragma once
#include "M_SignalGenerator_stub.hpp"   // generated by pipegen (struct types + IClient/IService shells)
#include <memory>
#include <string>

namespace M_SignalGenerator {

class Client {
public:
    static std::unique_ptr<Client> create(int domainId, std::string serviceName, IClient& cb);
    ~Client();

    // No-op IService command forwarders (stub implementation).
    void ConfigWaveform(::M_SignalGenerator::WaveformType const& /*unused*/) {}
    // Inline no-op IService command forwarders (stub).
    void ConfigGeneratorState(::std::uint32_t const& /*unused*/) {}
    void ConfigControllerOperationMode(::std::uint32_t const& /*unused*/) {}
    void ConfigControlMode(::std::uint32_t const& /*unused*/) {}
    void ConfigTestSetup(::std::uint32_t const& /*unused*/, ::std::uint32_t const& /*unused*/, ::std::uint32_t const& /*unused*/, ::M_Common::ULongListType const& /*unused*/) {}
    void ConfigAmplitudeScaling(::std::uint32_t const& /*unused*/, SampleListType const& /*unused*/) {}
    // Inline no-op IClient report forwarders (stub).
    void ReportGeneratorState(::std::uint32_t const& /*unused*/) {}
    void ReportControllerOperationMode(::std::uint32_t const& /*unused*/) {}
    void ReportControlMode(::std::uint32_t const& /*unused*/) {}
    void ReportTestMode(::std::uint32_t const& /*unused*/) {}
    void ReportTestAxis(::std::uint32_t const& /*unused*/) {}
    void ReportTestSource(::std::uint32_t const& /*unused*/) {}
    void EventSensorOutput(::M_Common::DoubleListType const& /*unused*/) {}



private:
    Client(int domain, std::string svc, IClient& cb);
    int sub_id_ = -1;
};

class Service {
public:
    static std::unique_ptr<Service> create(int domainId, std::string serviceName, IService& cb);
    ~Service();
    // Inline no-op IClient report forwarders (stub).
    void ReportGeneratorState(::std::uint32_t const& /*unused*/) {}
    void ReportControllerOperationMode(::std::uint32_t const& /*unused*/) {}
    void ReportControlMode(::std::uint32_t const& /*unused*/) {}
    void ReportTestMode(::std::uint32_t const& /*unused*/) {}
    void ReportTestAxis(::std::uint32_t const& /*unused*/) {}
    void ReportTestSource(::std::uint32_t const& /*unused*/) {}
    void EventSensorOutput(::M_Common::DoubleListType const& /*unused*/) {}
    // Inline no-op IService command forwarders (stub).
    void ConfigGeneratorState(::std::uint32_t const& /*unused*/) {}
    void ConfigControllerOperationMode(::std::uint32_t const& /*unused*/) {}
    void ConfigControlMode(::std::uint32_t const& /*unused*/) {}
    void ConfigTestSetup(::std::uint32_t const& /*unused*/, ::std::uint32_t const& /*unused*/, ::std::uint32_t const& /*unused*/, ::M_Common::ULongListType const& /*unused*/) {}
    void ConfigWaveform(WaveformType const& /*unused*/) {}
    void ConfigAmplitudeScaling(::std::uint32_t const& /*unused*/, SampleListType const& /*unused*/) {}



private:
    Service(int domain, std::string svc, IService& cb);
    int sub_id_ = -1;
};

}  // namespace M_SignalGenerator
