// SPDX-License-Identifier: MIT
// Stub SDK header for M_TerminalCtrl.
#pragma once
#include "M_TerminalCtrl_stub.hpp"   // generated by pipegen (struct types + IClient/IService shells)
#include <memory>
#include <string>

namespace M_TerminalCtrl {

class Client {
public:
    static std::unique_ptr<Client> create(int domainId, std::string serviceName, IClient& cb);
    ~Client();

    // No-op IService command forwarders (stub implementation).
    void ConfigMenuLanguage(::std::string const& /*unused*/) {}
    void CmdSetBlackoutMode(bool const& /*unused*/) {}
    // Inline no-op IService command forwarders (stub).
    void ConfigTerminalState(TerminalRequiredStateType const& /*unused*/, bool const& /*unused*/) {}
    void CmdExitMenu() {}
    void CmdIsTerminalAlive() {}
    // Inline no-op IClient report forwarders (stub).
    void ReportTerminalSettings(TerminalSettingsType const& /*unused*/) {}
    void ReportTerminalState(TerminalStateType const& /*unused*/, bool const& /*unused*/) {}



private:
    Client(int domain, std::string svc, IClient& cb);
    int sub_id_ = -1;
};

class Service {
public:
    static std::unique_ptr<Service> create(int domainId, std::string serviceName, IService& cb);
    ~Service();
    // Inline no-op IClient report forwarders (stub).
    void ReportTerminalSettings(TerminalSettingsType const& /*unused*/) {}
    void ReportTerminalState(TerminalStateType const& /*unused*/, bool const& /*unused*/) {}
    // Inline no-op IService command forwarders (stub).
    void ConfigTerminalState(TerminalRequiredStateType const& /*unused*/, bool const& /*unused*/) {}
    void ConfigMenuLanguage(::std::string const& /*unused*/) {}
    void CmdExitMenu() {}
    void CmdIsTerminalAlive() {}
    void CmdSetBlackoutMode(bool const& /*unused*/) {}



private:
    Service(int domain, std::string svc, IService& cb);
    int sub_id_ = -1;
};

}  // namespace M_TerminalCtrl
