// SPDX-License-Identifier: MIT
// Stub SDK header for M_Teleoperation.
#pragma once
#include "M_Teleoperation_stub.hpp"   // generated by pipegen (struct types + IClient/IService shells)
#include <memory>
#include <string>

namespace M_Teleoperation {

class Client {
public:
    static std::unique_ptr<Client> create(int domainId, std::string serviceName, IClient& cb);
    ~Client();
    // Inline no-op IClient report forwarders (stub).
    void ReportTeleoperationCtrlSettings(TeleoperationCtrlSettingsType const& /*unused*/) {}
    void ReportBatteryStatus(::std::string const& /*unused*/, BatteryStatusType const& /*unused*/, bool const& /*unused*/) {}
    void ReportRadioConnectionStatus(::std::string const& /*unused*/, RadioConnectionStatusType const& /*unused*/, bool const& /*unused*/) {}


private:
    Client(int domain, std::string svc, IClient& cb);
    int sub_id_ = -1;
};

class Service {
public:
    static std::unique_ptr<Service> create(int domainId, std::string serviceName, IService& cb);
    ~Service();
    // Inline no-op IClient report forwarders (stub).
    void ReportTeleoperationCtrlSettings(TeleoperationCtrlSettingsType const& /*unused*/) {}
    void ReportBatteryStatus(::std::string const& /*unused*/, BatteryStatusType const& /*unused*/, bool const& /*unused*/) {}
    void ReportRadioConnectionStatus(::std::string const& /*unused*/, RadioConnectionStatusType const& /*unused*/, bool const& /*unused*/) {}


private:
    Service(int domain, std::string svc, IService& cb);
    int sub_id_ = -1;
};

}  // namespace M_Teleoperation
