// SPDX-License-Identifier: MIT
// Stub SDK header for M_TimeManager.
#pragma once
#include "M_TimeManager_stub.hpp"   // generated by pipegen (struct types + IClient/IService shells)
#include <memory>
#include <string>

namespace M_TimeManager {

class Client {
public:
    static std::unique_ptr<Client> create(int domainId, std::string serviceName, IClient& cb);
    ~Client();

    // No-op IService command forwarders (stub implementation).
    void CmdAdvanceTime(::M_Common::DurationType const& /*unused*/) {}
    void CmdReverseTime(::M_Common::DurationType const& /*unused*/) {}
    // Inline no-op IService command forwarders (stub).
    void CmdSetTime(::M_Common::UtcType const& /*unused*/, TimeSourceType const& /*unused*/) {}
    void RequestTime() {}
    // Inline no-op IClient report forwarders (stub).
    void ReportTime(::M_Common::UtcType const& /*unused*/, TimeSourceType const& /*unused*/, bool const& /*unused*/) {}
    void ResponseTime(::M_Common::UtcType const& /*unused*/, TimeSourceType const& /*unused*/) {}



private:
    Client(int domain, std::string svc, IClient& cb);
    int sub_id_ = -1;
};

class Service {
public:
    static std::unique_ptr<Service> create(int domainId, std::string serviceName, IService& cb);
    ~Service();
    // Inline no-op IClient report forwarders (stub).
    void ReportTime(::M_Common::UtcType const& /*unused*/, TimeSourceType const& /*unused*/, bool const& /*unused*/) {}
    void ResponseTime(::M_Common::UtcType const& /*unused*/, TimeSourceType const& /*unused*/) {}
    // Inline no-op IService command forwarders (stub).
    void CmdSetTime(::M_Common::UtcType const& /*unused*/, TimeSourceType const& /*unused*/) {}
    void CmdAdvanceTime(::M_Common::DurationType const& /*unused*/) {}
    void CmdReverseTime(::M_Common::DurationType const& /*unused*/) {}
    void RequestTime() {}



private:
    Service(int domain, std::string svc, IService& cb);
    int sub_id_ = -1;
};

}  // namespace M_TimeManager
