// SPDX-License-Identifier: MIT
// Stub SDK header for M_VideoTrackerAtr.
#pragma once
#include "M_VideoTrackerAtr_stub.hpp"   // generated by pipegen (struct types + IClient/IService shells)
#include <memory>
#include <string>

namespace M_VideoTrackerAtr {

class Client {
public:
    static std::unique_ptr<Client> create(int domainId, std::string serviceName, IClient& cb);
    ~Client();

    // No-op IService command forwarders (stub implementation).
    void ConfigEnable(bool const& /*unused*/) {}
    // Inline no-op IService command forwarders (stub).
    void ConfigMinMaxObjectSize(::M_Common::PixelRectSizeType const& /*unused*/, ::M_Common::PixelRectSizeType const& /*unused*/) {}
    void CmdTeachIn(bool const& /*unused*/, bool const& /*unused*/) {}
    // Inline no-op IClient report forwarders (stub).
    void ReportAtrSettings(::M_VideoTracker::AtrSettingsType const& /*unused*/) {}
    void ReportAtrStatus(::M_VideoTracker::AtrStatusType const& /*unused*/, bool const& /*unused*/) {}



private:
    Client(int domain, std::string svc, IClient& cb);
    int sub_id_ = -1;
};

class Service {
public:
    static std::unique_ptr<Service> create(int domainId, std::string serviceName, IService& cb);
    ~Service();
    // Inline no-op IClient report forwarders (stub).
    void ReportAtrSettings(::M_VideoTracker::AtrSettingsType const& /*unused*/) {}
    void ReportAtrStatus(::M_VideoTracker::AtrStatusType const& /*unused*/, bool const& /*unused*/) {}
    // Inline no-op IService command forwarders (stub).
    void ConfigMinMaxObjectSize(::M_Common::PixelRectSizeType const& /*unused*/, ::M_Common::PixelRectSizeType const& /*unused*/) {}
    void ConfigEnable(bool const& /*unused*/) {}
    void CmdTeachIn(bool const& /*unused*/, bool const& /*unused*/) {}



private:
    Service(int domain, std::string svc, IService& cb);
    int sub_id_ = -1;
};

}  // namespace M_VideoTrackerAtr
