// SPDX-License-Identifier: MIT
// Stub SDK header for M_VideoMetadata.
#pragma once
#include "M_VideoMetadata_stub.hpp"   // generated by pipegen (struct types + IClient/IService shells)
#include <memory>
#include <string>

namespace M_VideoMetadata {

class Client {
public:
    static std::unique_ptr<Client> create(int domainId, std::string serviceName, IClient& cb);
    ~Client();
    // Inline no-op IClient report forwarders (stub).
    void EventRvtMetadata(RvtLS const& /*unused*/) {}
    void EventSecurityMetadata(SecurityMetadataLS const& /*unused*/) {}
    void EventSecurityMetadataUniversal(SecurityMetadataUniversalLS const& /*unused*/) {}
    void EventUasDatalinkLS(UasDatalinkLS const& /*unused*/) {}
    void EventVmtiLS(VmtiLS const& /*unused*/) {}
    void EventVTrackLS(VTrackLS const& /*unused*/) {}


private:
    Client(int domain, std::string svc, IClient& cb);
    int sub_id_ = -1;
};

class Service {
public:
    static std::unique_ptr<Service> create(int domainId, std::string serviceName, IService& cb);
    ~Service();
    // Inline no-op IClient report forwarders (stub).
    void EventRvtMetadata(RvtLS const& /*unused*/) {}
    void EventSecurityMetadata(SecurityMetadataLS const& /*unused*/) {}
    void EventSecurityMetadataUniversal(SecurityMetadataUniversalLS const& /*unused*/) {}
    void EventUasDatalinkLS(UasDatalinkLS const& /*unused*/) {}
    void EventVmtiLS(VmtiLS const& /*unused*/) {}
    void EventVTrackLS(VTrackLS const& /*unused*/) {}


private:
    Service(int domain, std::string svc, IService& cb);
    int sub_id_ = -1;
};

}  // namespace M_VideoMetadata
