// SPDX-License-Identifier: MIT
// Stub SDK header for M_VideoTrackerCommon.
#pragma once
#include "M_VideoTrackerCommon_stub.hpp"   // generated by pipegen (struct types + IClient/IService shells)
#include <memory>
#include <string>

namespace M_VideoTrackerCommon {

class Client {
public:
    static std::unique_ptr<Client> create(int domainId, std::string serviceName, IClient& cb);
    ~Client();

    // No-op IService command forwarders (stub implementation).
    void CmdLoadParameterSet(::M_Common::BoundedStringType const& /*unused*/) {}
    // Inline no-op IService command forwarders (stub).
    void CmdSelectObject(::M_Common::HorizontalDirectionOptionalType const& /*unused*/, ::M_Common::VerticalDirectionOptionalType const& /*unused*/, ::M_Common::SphericalPositionOptionalType const& /*unused*/) {}
    void ConfigVtTrackInfo(::M_Common::ObjectIdType const& /*unused*/, ::M_Sensor::SensorDetectionType const& /*unused*/, bool const& /*unused*/) {}
    // Inline no-op IClient report forwarders (stub).
    void ReportVtProcessingStat(::std::uint32_t const& /*unused*/, ::M_VideoTracker::VtProcessingStatType const& /*unused*/, bool const& /*unused*/) {}



private:
    Client(int domain, std::string svc, IClient& cb);
    int sub_id_ = -1;
};

class Service {
public:
    static std::unique_ptr<Service> create(int domainId, std::string serviceName, IService& cb);
    ~Service();
    // Inline no-op IClient report forwarders (stub).
    void ReportVtProcessingStat(::std::uint32_t const& /*unused*/, ::M_VideoTracker::VtProcessingStatType const& /*unused*/, bool const& /*unused*/) {}
    // Inline no-op IService command forwarders (stub).
    void CmdLoadParameterSet(::M_Common::BoundedStringType const& /*unused*/) {}
    void CmdSelectObject(::M_Common::HorizontalDirectionOptionalType const& /*unused*/, ::M_Common::VerticalDirectionOptionalType const& /*unused*/, ::M_Common::SphericalPositionOptionalType const& /*unused*/) {}
    void ConfigVtTrackInfo(::M_Common::ObjectIdType const& /*unused*/, ::M_Sensor::SensorDetectionType const& /*unused*/, bool const& /*unused*/) {}



private:
    Service(int domain, std::string svc, IService& cb);
    int sub_id_ = -1;
};

}  // namespace M_VideoTrackerCommon
