// SPDX-License-Identifier: MIT
// Stub SDK header for M_VideoObjectExport.
#pragma once
#include "M_VideoObjectExport_stub.hpp"   // generated by pipegen (struct types + IClient/IService shells)
#include <memory>
#include <string>

namespace M_VideoObjectExport {

class Client {
public:
    static std::unique_ptr<Client> create(int domainId, std::string serviceName, IClient& cb);
    ~Client();

    // No-op IService command forwarders (stub implementation).
    void ConfigRecorderExport(bool const& /*unused*/) {}
    // Inline no-op IClient report forwarders (stub).
    void ReportVideoObjectSettings(VideoObjectSettingsType const& /*unused*/) {}
    void ReportMountPosition(::std::string const& /*unused*/, ::M_Common::StringListType const& /*unused*/, ::M_Common::AngleDegreesType const& /*unused*/, ::M_Common::AngleDegreesType const& /*unused*/, bool const& /*unused*/) {}
    void ReportCameraZoomFovRegion(::std::string const& /*unused*/, ::M_Common::AngleDegreesType const& /*unused*/, ::M_Common::AngleDegreesType const& /*unused*/) {}
    void ReportMarkerObject(::M_Common::ObjectIdType const& /*unused*/, MarkerObjectType const& /*unused*/, bool const& /*unused*/) {}
    void ReportKinematicData(KinematicInfoType const& /*unused*/) {}


private:
    Client(int domain, std::string svc, IClient& cb);
    int sub_id_ = -1;
};

class Service {
public:
    static std::unique_ptr<Service> create(int domainId, std::string serviceName, IService& cb);
    ~Service();
    // Inline no-op IClient report forwarders (stub).
    void ReportVideoObjectSettings(VideoObjectSettingsType const& /*unused*/) {}
    void ReportMountPosition(::std::string const& /*unused*/, ::M_Common::StringListType const& /*unused*/, ::M_Common::AngleDegreesType const& /*unused*/, ::M_Common::AngleDegreesType const& /*unused*/, bool const& /*unused*/) {}
    void ReportCameraZoomFovRegion(::std::string const& /*unused*/, ::M_Common::AngleDegreesType const& /*unused*/, ::M_Common::AngleDegreesType const& /*unused*/) {}
    void ReportMarkerObject(::M_Common::ObjectIdType const& /*unused*/, MarkerObjectType const& /*unused*/, bool const& /*unused*/) {}
    void ReportKinematicData(KinematicInfoType const& /*unused*/) {}
    // Inline no-op IService command forwarders (stub).
    void ConfigRecorderExport(bool const& /*unused*/) {}



private:
    Service(int domain, std::string svc, IService& cb);
    int sub_id_ = -1;
};

}  // namespace M_VideoObjectExport
