// SPDX-License-Identifier: MIT
// Stub SDK header for M_VideoTrackerLot.
#pragma once
#include "M_VideoTrackerLot_stub.hpp"   // generated by pipegen (struct types + IClient/IService shells)
#include <memory>
#include <string>

namespace M_VideoTrackerLot {

class Client {
public:
    static std::unique_ptr<Client> create(int domainId, std::string serviceName, IClient& cb);
    ~Client();
    // Inline no-op IService command forwarders (stub).
    void ConfigDefaultGateSizes(::M_Common::PixelRectSizeOptionalType const& /*unused*/, ::M_Common::PixelRectSizeOptionalType const& /*unused*/) {}
    void CmdLockOnAtPos(::M_Common::PixelRegionType const& /*unused*/, ::M_Common::PixelRectSizeOptionalType const& /*unused*/, ::M_VideoTracker::LotModeOptionalType const& /*unused*/, bool const& /*unused*/) {}
    void CmdLockOnTrack(::M_Common::ObjectIdOptionalType const& /*unused*/, bool const& /*unused*/) {}
    void CmdManualGateControl(::M_Common::ObjectIdOptionalType const& /*unused*/, ::std::int32_t const& /*unused*/, ::std::int32_t const& /*unused*/) {}
    void CmdAutoGateControl(::M_Common::ObjectIdOptionalType const& /*unused*/) {}
    void CmdForceCoasting(::M_Common::ObjectIdOptionalType const& /*unused*/, bool const& /*unused*/) {}
    // Inline no-op IClient report forwarders (stub).
    void ReportLotStatus(::M_VideoTracker::LotStatusType const& /*unused*/, bool const& /*unused*/) {}



private:
    Client(int domain, std::string svc, IClient& cb);
    int sub_id_ = -1;
};

class Service {
public:
    static std::unique_ptr<Service> create(int domainId, std::string serviceName, IService& cb);
    ~Service();
    // Inline no-op IClient report forwarders (stub).
    void ReportLotStatus(::M_VideoTracker::LotStatusType const& /*unused*/, bool const& /*unused*/) {}
    // Inline no-op IService command forwarders (stub).
    void ConfigDefaultGateSizes(::M_Common::PixelRectSizeOptionalType const& /*unused*/, ::M_Common::PixelRectSizeOptionalType const& /*unused*/) {}
    void CmdLockOnAtPos(::M_Common::PixelRegionType const& /*unused*/, ::M_Common::PixelRectSizeOptionalType const& /*unused*/, ::M_VideoTracker::LotModeOptionalType const& /*unused*/, bool const& /*unused*/) {}
    void CmdLockOnTrack(::M_Common::ObjectIdOptionalType const& /*unused*/, bool const& /*unused*/) {}
    void CmdManualGateControl(::M_Common::ObjectIdOptionalType const& /*unused*/, ::std::int32_t const& /*unused*/, ::std::int32_t const& /*unused*/) {}
    void CmdAutoGateControl(::M_Common::ObjectIdOptionalType const& /*unused*/) {}
    void CmdForceCoasting(::M_Common::ObjectIdOptionalType const& /*unused*/, bool const& /*unused*/) {}



private:
    Service(int domain, std::string svc, IService& cb);
    int sub_id_ = -1;
};

}  // namespace M_VideoTrackerLot
