// SPDX-License-Identifier: MIT
// Stub SDK header for M_VideoTrackerLosCtrl.
#pragma once
#include "M_VideoTrackerLosCtrl_stub.hpp"   // generated by pipegen (struct types + IClient/IService shells)
#include <memory>
#include <string>

namespace M_VideoTrackerLosCtrl {

class Client {
public:
    static std::unique_ptr<Client> create(int domainId, std::string serviceName, IClient& cb);
    ~Client();

    // No-op IService command forwarders (stub implementation).
    void ConfigHelpRateInputSource(::std::string const& /*unused*/) {}
    void CmdApdAbsolute(::M_Common::SphericalPositionType const& /*unused*/) {}
    void CmdApdByCenterOffset(::M_Common::SphericalPositionType const& /*unused*/) {}
    void ConfigAutoLeadOn(bool const& /*unused*/) {}
    void NotifyHelpRate(::M_Common::AngularVelocityType const& /*unused*/) {}
    // Inline no-op IService command forwarders (stub).
    void CmdLeadOn(::M_Common::ObjectIdOptionalType const& /*unused*/) {}
    void CmdApdByStep(::std::int32_t const& /*unused*/, ::std::int32_t const& /*unused*/) {}
    void NotifyMountTrackingState(::M_VideoTracker::MountTrackingState::Type const& /*unused*/) {}
    // Inline no-op IClient report forwarders (stub).
    void ReportLosCtrlStatus(::M_VideoTracker::LosCtrlStatusType const& /*unused*/, bool const& /*unused*/) {}
    void ReportRate(::M_Common::AngularVelocityType const& /*unused*/, bool const& /*unused*/, bool const& /*unused*/) {}
    void ReportPosError(::M_Common::PositionType const& /*unused*/, bool const& /*unused*/, bool const& /*unused*/) {}
    void ReportMaxCenteringRate(::M_Common::AngularVelocityType const& /*unused*/) {}
    void ReportApd(::M_Common::PositionType const& /*unused*/) {}



private:
    Client(int domain, std::string svc, IClient& cb);
    int sub_id_ = -1;
};

class Service {
public:
    static std::unique_ptr<Service> create(int domainId, std::string serviceName, IService& cb);
    ~Service();
    // Inline no-op IClient report forwarders (stub).
    void ReportLosCtrlStatus(::M_VideoTracker::LosCtrlStatusType const& /*unused*/, bool const& /*unused*/) {}
    void ReportRate(::M_Common::AngularVelocityType const& /*unused*/, bool const& /*unused*/, bool const& /*unused*/) {}
    void ReportPosError(::M_Common::PositionType const& /*unused*/, bool const& /*unused*/, bool const& /*unused*/) {}
    void ReportMaxCenteringRate(::M_Common::AngularVelocityType const& /*unused*/) {}
    void ReportApd(::M_Common::PositionType const& /*unused*/) {}
    // Inline no-op IService command forwarders (stub).
    void ConfigHelpRateInputSource(::std::string const& /*unused*/) {}
    void CmdLeadOn(::M_Common::ObjectIdOptionalType const& /*unused*/) {}
    void CmdApdAbsolute(::M_Common::SphericalPositionType const& /*unused*/) {}
    void CmdApdByStep(::std::int32_t const& /*unused*/, ::std::int32_t const& /*unused*/) {}
    void CmdApdByCenterOffset(::M_Common::SphericalPositionType const& /*unused*/) {}
    void ConfigAutoLeadOn(bool const& /*unused*/) {}
    void NotifyMountTrackingState(::M_VideoTracker::MountTrackingState::Type const& /*unused*/) {}
    void NotifyHelpRate(::M_Common::AngularVelocityType const& /*unused*/) {}



private:
    Service(int domain, std::string svc, IService& cb);
    int sub_id_ = -1;
};

}  // namespace M_VideoTrackerLosCtrl
