// SPDX-License-Identifier: MIT
// Stub SDK header for M_VideoManager.
#pragma once
#include "M_VideoManager_stub.hpp"   // generated by pipegen (struct types + IClient/IService shells)
#include <memory>
#include <string>

namespace M_VideoManager {

class Client {
public:
    static std::unique_ptr<Client> create(int domainId, std::string serviceName, IClient& cb);
    ~Client();

    // No-op IService command forwarders (stub implementation).
    void CmdFovCoupling(bool const& /*unused*/) {}
    void ConfigVideoChannel(::std::string const& /*unused*/) {}
    // Inline no-op IClient report forwarders (stub).
    void ReportVideoSettings(VmSettingsType const& /*unused*/) {}
    void ReportVideoStatus(VmStatusType const& /*unused*/, bool const& /*unused*/) {}


private:
    Client(int domain, std::string svc, IClient& cb);
    int sub_id_ = -1;
};

class Service {
public:
    static std::unique_ptr<Service> create(int domainId, std::string serviceName, IService& cb);
    ~Service();
    // Inline no-op IClient report forwarders (stub).
    void ReportVideoSettings(VmSettingsType const& /*unused*/) {}
    void ReportVideoStatus(VmStatusType const& /*unused*/, bool const& /*unused*/) {}
    // Inline no-op IService command forwarders (stub).
    void CmdFovCoupling(bool const& /*unused*/) {}
    void ConfigVideoChannel(::std::string const& /*unused*/) {}



private:
    Service(int domain, std::string svc, IService& cb);
    int sub_id_ = -1;
};

}  // namespace M_VideoManager
