// SPDX-License-Identifier: MIT
// Stub SDK header for M_Watchdog.
#pragma once
#include "M_Watchdog_stub.hpp"   // generated by pipegen (struct types + IClient/IService shells)
#include <memory>
#include <string>

namespace M_Watchdog {

class Client {
public:
    static std::unique_ptr<Client> create(int domainId, std::string serviceName, IClient& cb);
    ~Client();
    // Inline no-op IService command forwarders (stub).
    void ConfigWatch(::std::string const& /*unused*/, ::std::string const& /*unused*/, ::M_Common::StringListType const& /*unused*/, bool const& /*unused*/) {}
    // Inline no-op IClient report forwarders (stub).
    void ReportWatchdogSettings(WatchdogSettingsType const& /*unused*/) {}
    void ReportWatchStatus(::std::string const& /*unused*/, ::std::string const& /*unused*/, WatchStatusType const& /*unused*/, bool const& /*unused*/) {}



private:
    Client(int domain, std::string svc, IClient& cb);
    int sub_id_ = -1;
};

class Service {
public:
    static std::unique_ptr<Service> create(int domainId, std::string serviceName, IService& cb);
    ~Service();
    // Inline no-op IClient report forwarders (stub).
    void ReportWatchdogSettings(WatchdogSettingsType const& /*unused*/) {}
    void ReportWatchStatus(::std::string const& /*unused*/, ::std::string const& /*unused*/, WatchStatusType const& /*unused*/, bool const& /*unused*/) {}
    // Inline no-op IService command forwarders (stub).
    void ConfigWatch(::std::string const& /*unused*/, ::std::string const& /*unused*/, ::M_Common::StringListType const& /*unused*/, bool const& /*unused*/) {}



private:
    Service(int domain, std::string svc, IService& cb);
    int sub_id_ = -1;
};

}  // namespace M_Watchdog
