// SPDX-License-Identifier: MIT
#include <filesystem>
#include <fstream>
#include <iostream>
#include <map>
#include <set>
#include <sstream>
#include "lexer.hpp"
#include "parser.hpp"
#include "emit_cpp.hpp"
#include "emit_stub.hpp"
#include "emit_ts.hpp"

namespace fs = std::filesystem;

static std::string slurp(fs::path const& p) {
    std::ifstream f(p);
    std::ostringstream os; os << f.rdbuf();
    return os.str();
}

int main(int argc, char** argv) {
    if (argc < 3) {
        std::cerr << "usage: pipegen <out-dir> <rmodel-file> [<rmodel-file>...] [--stub-out DIR] [--ts-out DIR]\n";
        return 64;
    }

    // Extract optional flags before positional parsing.
    std::string stub_out_dir;
    std::string ts_out_dir;
    bool target_real_sdk = false;
    std::vector<std::string> args;
    for (int i = 1; i < argc; ++i) {
        std::string a = argv[i];
        if (a == "--stub-out") {
            if (i + 1 < argc) {
                stub_out_dir = argv[++i];
            } else {
                std::cerr << "pipegen: --stub-out requires a directory argument\n";
                return 64;
            }
        } else if (a == "--ts-out") {
            if (i + 1 < argc) {
                ts_out_dir = argv[++i];
            } else {
                std::cerr << "pipegen: --ts-out requires a directory argument\n";
                return 64;
            }
        } else if (a == "--real-sdk") {
            target_real_sdk = true;
        } else {
            args.push_back(std::move(a));
        }
    }

    if (args.size() < 2) {
        std::cerr << "usage: pipegen <out-dir> <rmodel-file> [<rmodel-file>...] [--stub-out DIR] [--ts-out DIR]\n";
        return 64;
    }

    fs::path out = args[0];
    fs::create_directories(out);

    if (!stub_out_dir.empty())
        fs::create_directories(stub_out_dir);

    if (!ts_out_dir.empty())
        fs::create_directories(ts_out_dir);

    std::ostringstream registry;
    registry << "// AUTO-GENERATED by pipegen. Do not edit.\n"
                "// SPDX-License-Identifier: MIT\n"
                "#include \"flowboard/registry.hpp\"\n"
                "#include \"flowboard/node.hpp\"\n";

    std::vector<std::string> ts_module_names;

    // Merge modules by name across files so M_Foo (interface) and M_Foo (types) become one emit.
    std::map<std::string, std::vector<pipegen::ast::ModulePtr>> merged;
    for (std::size_t i = 1; i < args.size(); ++i) {
        try {
            auto src = slurp(args[i]);
            auto file = pipegen::parse(pipegen::lex(src));
            for (auto& m : file.modules) merged[m->name].push_back(m);
        } catch (std::exception const& e) {
            std::cerr << "pipegen: " << args[i] << ": " << e.what() << "\n";
            return 65;
        }
    }
    // Build the full set of known module names so emit_cpp_for_module can classify
    // cross-module type references correctly (dynamic replacement for kKnownModules).
    std::set<std::string> known_modules;
    for (auto const& [name, _] : merged)
        known_modules.insert(name);

    // Build the full cross-module typedef map keyed by fully-qualified name
    // (e.g. "M_Common::AngleDegreesOptionalType"). emit_cpp_for_module needs this
    // to resolve typedef chains when classifying struct fields and emitting the
    // per-struct Extract factory.
    std::map<std::string, pipegen::ast::TypeRef> all_typedefs;
    for (auto const& [mod_name, parts] : merged) {
        for (auto const& p : parts) {
            for (auto const& td : p->typedefs) {
                all_typedefs[mod_name + "::" + td.name] = *td.aliased;
            }
        }
    }

    for (auto& [name, parts] : merged) {
        pipegen::ast::Module combined;
        combined.name = name;
        // Maintain a global offset so that source_order is monotonically increasing
        // across merged module parts (e.g., MountTypes.rmodel then Mount.rmodel).
        std::size_t order_offset = 0;
        for (auto& p : parts) {
            std::size_t max_order = 0;
            for (auto& sub : p->submodules)  combined.submodules.push_back(sub);
            for (auto& e : p->enums)         combined.enums.push_back(e);
            for (auto& s : p->structs) {
                auto sc = s;
                sc.source_order += order_offset;
                if (sc.source_order > max_order) max_order = sc.source_order;
                combined.structs.push_back(std::move(sc));
            }
            for (auto& t : p->typedefs) {
                auto tc = t;
                tc.source_order += order_offset;
                if (tc.source_order > max_order) max_order = tc.source_order;
                combined.typedefs.push_back(std::move(tc));
            }
            for (auto& c : p->consts)        combined.consts.push_back(c);
            for (auto& i : p->interfaces)    combined.interfaces.push_back(i);
            order_offset = max_order + 1;
        }
        auto e = pipegen::emit_cpp_for_module(combined, known_modules, all_typedefs, target_real_sdk);
        std::ofstream htypes(out / (name + "_types.hpp"));    htypes << e.types_hpp;
        std::ofstream nodes (out / (name + "_nodes.cpp"));    nodes  << e.nodes_cpp;
        registry << "#include \"" << name << "_types.hpp\"\n";
        registry << e.registry_snippet;

        if (!stub_out_dir.empty()) {
            auto s = pipegen::emit_stub_header(combined);
            std::ofstream f(fs::path(stub_out_dir) / (name + "_stub.hpp"));
            f << s;
        }

        if (!ts_out_dir.empty()) {
            auto ts = pipegen::emit_ts_module(combined, known_modules, all_typedefs);
            std::ofstream f(fs::path(ts_out_dir) / (name + "_types.ts"));
            f << ts;
            ts_module_names.push_back(name);
        }
    }
    std::ofstream reg(out / "registry_init.cpp"); reg << registry.str();

    if (!ts_out_dir.empty()) {
        // index.ts: re-export the per-module struct-name arrays. Use NAMED
        // re-exports (not wildcard) so the FieldKind/FieldDescriptor types
        // each module's _types.ts exports don't collide via TS2308.
        std::ostringstream index;
        index << "// AUTO-GENERATED. Do not edit.\n";
        index << "// SPDX-License-Identifier: MIT\n";
        for (auto const& n : ts_module_names) {
            index << "export { " << n << "_types } from './" << n << "_types';\n";
        }
        std::ofstream f(fs::path(ts_out_dir) / "index.ts");
        f << index.str();

        // Separate barrel for the field descriptors — imported by the web
        // helper `web/src/lib/extract_ports.ts` (Task 11).
        std::ofstream fd(fs::path(ts_out_dir) / "field_descriptors.generated.ts");
        fd << pipegen::emit_ts_barrel(ts_module_names);
    }

    std::cout << "pipegen: wrote " << merged.size() << " module(s) to " << out << "\n";
    return 0;
}
