# SPDX-License-Identifier: MIT
# Generate a C++ source file containing every file under <src_dir> as a string,
# exposed via `std::string const* web_asset(std::string const& path)`.
#
# Usage:
#   flowboard_embed_web_assets(<target> <src_dir> <out_cpp>)
#
# Generates <out_cpp> at build time via cmake -P.
# Large assets are split into chunks of <= 8000 hex-escaped bytes (16000 chars)
# to stay within MSVC's string-literal length limit (C2026).
#
# The generated TU defines:
#   namespace flowboard::control {
#     std::string const* web_asset(std::string const& path);
#   }

function(flowboard_embed_web_assets target src_dir out_cpp)
    if(NOT EXISTS "${src_dir}")
        message(WARNING "EmbedWebAssets: ${src_dir} does not exist; build the web bundle first.")
    endif()

    # Ensure the output directory exists at configure time.
    get_filename_component(_out_dir "${out_cpp}" DIRECTORY)
    file(MAKE_DIRECTORY "${_out_dir}")

    # Write a self-contained cmake -P script with paths baked in
    # (avoids -D quoting problems on Windows/MSBuild).
    set(_script "${CMAKE_BINARY_DIR}/embed-web-${target}.cmake")

    cmake_path(CONVERT "${src_dir}" TO_CMAKE_PATH_LIST _src_fwd NORMALIZE)
    cmake_path(CONVERT "${out_cpp}" TO_CMAKE_PATH_LIST _out_fwd NORMALIZE)

    # MSVC limits string literals to ~16380 chars (C2026).
    # Each byte becomes 4 chars (\xNN), so chunk at 4000 bytes = 16000 chars.
    set(_chunk_bytes 4000)

    file(WRITE "${_script}"
"cmake_minimum_required(VERSION 3.20)
set(SRC_DIR \"${_src_fwd}\")
set(OUT_CPP \"${_out_fwd}\")
set(CHUNK_BYTES ${_chunk_bytes})

file(GLOB_RECURSE _files RELATIVE \"\${SRC_DIR}\" \"\${SRC_DIR}/*\")
list(SORT _files)

set(_OUT \"\")
string(APPEND _OUT \"// AUTO-GENERATED by cmake/EmbedWebAssets.cmake. Do not edit.\\n\")
string(APPEND _OUT \"// SPDX-License-Identifier: MIT\\n\")
string(APPEND _OUT \"#include <string>\\n\")
string(APPEND _OUT \"#include <unordered_map>\\n\")
string(APPEND _OUT \"namespace flowboard::control {\\n\")
string(APPEND _OUT \"static const std::unordered_map<std::string,std::string> kWebAssets = {\\n\")

foreach(_f IN LISTS _files)
    file(READ \"\${SRC_DIR}/\${_f}\" _bytes HEX)
    string(LENGTH \"\${_bytes}\" _hexlen)
    math(EXPR _binlen \"\${_hexlen} / 2\")
    string(REPLACE \"\\\\\" \"/\" _fwd \"\${_f}\")

    # Each byte is two hex chars; chunk boundary is CHUNK_BYTES * 2 hex chars.
    math(EXPR _chunk_hex \"\${CHUNK_BYTES} * 2\")

    # Build the value expression as concatenated string literals to avoid
    # MSVC C2026 (string literal too long, limit ~16380 chars).
    set(_val_expr \"\")
    set(_pos 0)
    while(_pos LESS _hexlen)
        math(EXPR _end \"\${_pos} + \${_chunk_hex}\")
        if(_end GREATER _hexlen)
            set(_end \${_hexlen})
        endif()
        math(EXPR _chunk_len \"\${_end} - \${_pos}\")
        string(SUBSTRING \"\${_bytes}\" \${_pos} \${_chunk_len} _chunk_hex_str)
        string(REGEX REPLACE \"(..)\" \"\\\\\\\\x\\\\1\" _chunk_esc \"\${_chunk_hex_str}\")
        if(_val_expr STREQUAL \"\")
            set(_val_expr \"std::string(\\\"\${_chunk_esc}\\\", \${_chunk_len}/2)\")
        else()
            string(APPEND _val_expr \" + std::string(\\\"\${_chunk_esc}\\\", \${_chunk_len}/2)\")
        endif()
        math(EXPR _pos \"\${_pos} + \${_chunk_hex}\")
    endwhile()

    if(_val_expr STREQUAL \"\")
        # Empty file
        set(_val_expr \"std::string()\")
    endif()

    string(APPEND _OUT \"  {\\\"/\${_fwd}\\\", \${_val_expr}},\\n\")
endforeach()

string(APPEND _OUT \"};\\n\")
string(APPEND _OUT \"std::string const* web_asset(std::string const& p) {\\n\")
string(APPEND _OUT \"  auto it = kWebAssets.find(p); return it == kWebAssets.end() ? nullptr : &it->second;\\n\")
string(APPEND _OUT \"}\\n\")
string(APPEND _OUT \"}  // namespace flowboard::control\\n\")

file(WRITE \"\${OUT_CPP}\" \"\${_OUT}\")
message(STATUS \"EmbedWebAssets: wrote \${OUT_CPP} (${_binlen} total bytes)\")
")

    # Collect all files in src_dir at configure time for dependency tracking.
    file(GLOB_RECURSE _dep_files "${src_dir}/*")

    add_custom_command(
        OUTPUT  "${out_cpp}"
        COMMAND "${CMAKE_COMMAND}" -P "${_script}"
        DEPENDS ${_dep_files}
        COMMENT "Embedding web assets from ${src_dir} -> ${out_cpp}"
        VERBATIM)

    target_sources(${target} PRIVATE "${out_cpp}")
endfunction()
